// Code generated by ent, DO NOT EDIT.

package openaidualattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaidualattempt type in the database.
	Label = "open_ai_dual_attempt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAttemptID holds the string denoting the attempt_id field in the database.
	FieldAttemptID = "attempt_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldServiceTier holds the string denoting the service_tier field in the database.
	FieldServiceTier = "service_tier"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBillingBasis holds the string denoting the billing_basis field in the database.
	FieldBillingBasis = "billing_basis"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldBilledCost holds the string denoting the billed_cost field in the database.
	FieldBilledCost = "billed_cost"
	// FieldUpstreamDispatchedAt holds the string denoting the upstream_dispatched_at field in the database.
	FieldUpstreamDispatchedAt = "upstream_dispatched_at"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the openaidualattempt in the database.
	Table = "openai_dual_attempts"
)

// Columns holds all SQL columns for openaidualattempt fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldAttemptID,
	FieldAPIKeyID,
	FieldUserID,
	FieldAccountID,
	FieldEndpoint,
	FieldMethod,
	FieldRole,
	FieldOutcome,
	FieldServiceTier,
	FieldStatus,
	FieldBillingBasis,
	FieldEstimatedCost,
	FieldActualCost,
	FieldBilledCost,
	FieldUpstreamDispatchedAt,
	FieldCancelReason,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// AttemptIDValidator is a validator for the "attempt_id" field. It is called by the builders before save.
	AttemptIDValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultOutcome holds the default value on creation for the "outcome" field.
	DefaultOutcome string
	// OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	OutcomeValidator func(string) error
	// ServiceTierValidator is a validator for the "service_tier" field. It is called by the builders before save.
	ServiceTierValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// BillingBasisValidator is a validator for the "billing_basis" field. It is called by the builders before save.
	BillingBasisValidator func(string) error
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// DefaultBilledCost holds the default value on creation for the "billed_cost" field.
	DefaultBilledCost float64
	// CancelReasonValidator is a validator for the "cancel_reason" field. It is called by the builders before save.
	CancelReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAIDualAttempt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAttemptID orders the results by the attempt_id field.
func ByAttemptID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByServiceTier orders the results by the service_tier field.
func ByServiceTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceTier, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBillingBasis orders the results by the billing_basis field.
func ByBillingBasis(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingBasis, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByBilledCost orders the results by the billed_cost field.
func ByBilledCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBilledCost, opts...).ToFunc()
}

// ByUpstreamDispatchedAt orders the results by the upstream_dispatched_at field.
func ByUpstreamDispatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamDispatchedAt, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
