// Code generated by ent, DO NOT EDIT.

package openaidualattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldRequestID, v))
}

// AttemptID applies equality check predicate on the "attempt_id" field. It's identical to AttemptIDEQ.
func AttemptID(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAttemptID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAccountID, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldEndpoint, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldMethod, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldRole, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldOutcome, v))
}

// ServiceTier applies equality check predicate on the "service_tier" field. It's identical to ServiceTierEQ.
func ServiceTier(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldServiceTier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldStatus, v))
}

// BillingBasis applies equality check predicate on the "billing_basis" field. It's identical to BillingBasisEQ.
func BillingBasis(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldBillingBasis, v))
}

// EstimatedCost applies equality check predicate on the "estimated_cost" field. It's identical to EstimatedCostEQ.
func EstimatedCost(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldEstimatedCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldActualCost, v))
}

// BilledCost applies equality check predicate on the "billed_cost" field. It's identical to BilledCostEQ.
func BilledCost(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldBilledCost, v))
}

// UpstreamDispatchedAt applies equality check predicate on the "upstream_dispatched_at" field. It's identical to UpstreamDispatchedAtEQ.
func UpstreamDispatchedAt(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUpstreamDispatchedAt, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldCancelReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldRequestID, v))
}

// AttemptIDEQ applies the EQ predicate on the "attempt_id" field.
func AttemptIDEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAttemptID, v))
}

// AttemptIDNEQ applies the NEQ predicate on the "attempt_id" field.
func AttemptIDNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldAttemptID, v))
}

// AttemptIDIn applies the In predicate on the "attempt_id" field.
func AttemptIDIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldAttemptID, vs...))
}

// AttemptIDNotIn applies the NotIn predicate on the "attempt_id" field.
func AttemptIDNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldAttemptID, vs...))
}

// AttemptIDGT applies the GT predicate on the "attempt_id" field.
func AttemptIDGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldAttemptID, v))
}

// AttemptIDGTE applies the GTE predicate on the "attempt_id" field.
func AttemptIDGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldAttemptID, v))
}

// AttemptIDLT applies the LT predicate on the "attempt_id" field.
func AttemptIDLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldAttemptID, v))
}

// AttemptIDLTE applies the LTE predicate on the "attempt_id" field.
func AttemptIDLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldAttemptID, v))
}

// AttemptIDContains applies the Contains predicate on the "attempt_id" field.
func AttemptIDContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldAttemptID, v))
}

// AttemptIDHasPrefix applies the HasPrefix predicate on the "attempt_id" field.
func AttemptIDHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldAttemptID, v))
}

// AttemptIDHasSuffix applies the HasSuffix predicate on the "attempt_id" field.
func AttemptIDHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldAttemptID, v))
}

// AttemptIDEqualFold applies the EqualFold predicate on the "attempt_id" field.
func AttemptIDEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldAttemptID, v))
}

// AttemptIDContainsFold applies the ContainsFold predicate on the "attempt_id" field.
func AttemptIDContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldAttemptID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldAPIKeyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldAccountID))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldEndpoint, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldMethod, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldRole, v))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldOutcome, v))
}

// ServiceTierEQ applies the EQ predicate on the "service_tier" field.
func ServiceTierEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldServiceTier, v))
}

// ServiceTierNEQ applies the NEQ predicate on the "service_tier" field.
func ServiceTierNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldServiceTier, v))
}

// ServiceTierIn applies the In predicate on the "service_tier" field.
func ServiceTierIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldServiceTier, vs...))
}

// ServiceTierNotIn applies the NotIn predicate on the "service_tier" field.
func ServiceTierNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldServiceTier, vs...))
}

// ServiceTierGT applies the GT predicate on the "service_tier" field.
func ServiceTierGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldServiceTier, v))
}

// ServiceTierGTE applies the GTE predicate on the "service_tier" field.
func ServiceTierGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldServiceTier, v))
}

// ServiceTierLT applies the LT predicate on the "service_tier" field.
func ServiceTierLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldServiceTier, v))
}

// ServiceTierLTE applies the LTE predicate on the "service_tier" field.
func ServiceTierLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldServiceTier, v))
}

// ServiceTierContains applies the Contains predicate on the "service_tier" field.
func ServiceTierContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldServiceTier, v))
}

// ServiceTierHasPrefix applies the HasPrefix predicate on the "service_tier" field.
func ServiceTierHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldServiceTier, v))
}

// ServiceTierHasSuffix applies the HasSuffix predicate on the "service_tier" field.
func ServiceTierHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldServiceTier, v))
}

// ServiceTierIsNil applies the IsNil predicate on the "service_tier" field.
func ServiceTierIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldServiceTier))
}

// ServiceTierNotNil applies the NotNil predicate on the "service_tier" field.
func ServiceTierNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldServiceTier))
}

// ServiceTierEqualFold applies the EqualFold predicate on the "service_tier" field.
func ServiceTierEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldServiceTier, v))
}

// ServiceTierContainsFold applies the ContainsFold predicate on the "service_tier" field.
func ServiceTierContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldServiceTier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldStatus, v))
}

// BillingBasisEQ applies the EQ predicate on the "billing_basis" field.
func BillingBasisEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldBillingBasis, v))
}

// BillingBasisNEQ applies the NEQ predicate on the "billing_basis" field.
func BillingBasisNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldBillingBasis, v))
}

// BillingBasisIn applies the In predicate on the "billing_basis" field.
func BillingBasisIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldBillingBasis, vs...))
}

// BillingBasisNotIn applies the NotIn predicate on the "billing_basis" field.
func BillingBasisNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldBillingBasis, vs...))
}

// BillingBasisGT applies the GT predicate on the "billing_basis" field.
func BillingBasisGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldBillingBasis, v))
}

// BillingBasisGTE applies the GTE predicate on the "billing_basis" field.
func BillingBasisGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldBillingBasis, v))
}

// BillingBasisLT applies the LT predicate on the "billing_basis" field.
func BillingBasisLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldBillingBasis, v))
}

// BillingBasisLTE applies the LTE predicate on the "billing_basis" field.
func BillingBasisLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldBillingBasis, v))
}

// BillingBasisContains applies the Contains predicate on the "billing_basis" field.
func BillingBasisContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldBillingBasis, v))
}

// BillingBasisHasPrefix applies the HasPrefix predicate on the "billing_basis" field.
func BillingBasisHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldBillingBasis, v))
}

// BillingBasisHasSuffix applies the HasSuffix predicate on the "billing_basis" field.
func BillingBasisHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldBillingBasis, v))
}

// BillingBasisIsNil applies the IsNil predicate on the "billing_basis" field.
func BillingBasisIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldBillingBasis))
}

// BillingBasisNotNil applies the NotNil predicate on the "billing_basis" field.
func BillingBasisNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldBillingBasis))
}

// BillingBasisEqualFold applies the EqualFold predicate on the "billing_basis" field.
func BillingBasisEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldBillingBasis, v))
}

// BillingBasisContainsFold applies the ContainsFold predicate on the "billing_basis" field.
func BillingBasisContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldBillingBasis, v))
}

// EstimatedCostEQ applies the EQ predicate on the "estimated_cost" field.
func EstimatedCostEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldEstimatedCost, v))
}

// EstimatedCostNEQ applies the NEQ predicate on the "estimated_cost" field.
func EstimatedCostNEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldEstimatedCost, v))
}

// EstimatedCostIn applies the In predicate on the "estimated_cost" field.
func EstimatedCostIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldEstimatedCost, vs...))
}

// EstimatedCostNotIn applies the NotIn predicate on the "estimated_cost" field.
func EstimatedCostNotIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldEstimatedCost, vs...))
}

// EstimatedCostGT applies the GT predicate on the "estimated_cost" field.
func EstimatedCostGT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldEstimatedCost, v))
}

// EstimatedCostGTE applies the GTE predicate on the "estimated_cost" field.
func EstimatedCostGTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldEstimatedCost, v))
}

// EstimatedCostLT applies the LT predicate on the "estimated_cost" field.
func EstimatedCostLT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldEstimatedCost, v))
}

// EstimatedCostLTE applies the LTE predicate on the "estimated_cost" field.
func EstimatedCostLTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldEstimatedCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldActualCost, v))
}

// BilledCostEQ applies the EQ predicate on the "billed_cost" field.
func BilledCostEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldBilledCost, v))
}

// BilledCostNEQ applies the NEQ predicate on the "billed_cost" field.
func BilledCostNEQ(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldBilledCost, v))
}

// BilledCostIn applies the In predicate on the "billed_cost" field.
func BilledCostIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldBilledCost, vs...))
}

// BilledCostNotIn applies the NotIn predicate on the "billed_cost" field.
func BilledCostNotIn(vs ...float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldBilledCost, vs...))
}

// BilledCostGT applies the GT predicate on the "billed_cost" field.
func BilledCostGT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldBilledCost, v))
}

// BilledCostGTE applies the GTE predicate on the "billed_cost" field.
func BilledCostGTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldBilledCost, v))
}

// BilledCostLT applies the LT predicate on the "billed_cost" field.
func BilledCostLT(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldBilledCost, v))
}

// BilledCostLTE applies the LTE predicate on the "billed_cost" field.
func BilledCostLTE(v float64) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldBilledCost, v))
}

// UpstreamDispatchedAtEQ applies the EQ predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtNEQ applies the NEQ predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtNEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtIn applies the In predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldUpstreamDispatchedAt, vs...))
}

// UpstreamDispatchedAtNotIn applies the NotIn predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtNotIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldUpstreamDispatchedAt, vs...))
}

// UpstreamDispatchedAtGT applies the GT predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtGT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtGTE applies the GTE predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtGTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtLT applies the LT predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtLT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtLTE applies the LTE predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtLTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldUpstreamDispatchedAt, v))
}

// UpstreamDispatchedAtIsNil applies the IsNil predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldUpstreamDispatchedAt))
}

// UpstreamDispatchedAtNotNil applies the NotNil predicate on the "upstream_dispatched_at" field.
func UpstreamDispatchedAtNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldUpstreamDispatchedAt))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonIsNil applies the IsNil predicate on the "cancel_reason" field.
func CancelReasonIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldCancelReason))
}

// CancelReasonNotNil applies the NotNil predicate on the "cancel_reason" field.
func CancelReasonNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldCancelReason))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldContainsFold(FieldCancelReason, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIDualAttempt) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIDualAttempt) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIDualAttempt) predicate.OpenAIDualAttempt {
	return predicate.OpenAIDualAttempt(sql.NotPredicates(p))
}
