// Code generated by ent, DO NOT EDIT.

package uservipmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the uservipmembership type in the database.
	Label = "user_vip_membership"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldVipLevelID holds the string denoting the vip_level_id field in the database.
	FieldVipLevelID = "vip_level_id"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSourceOrderID holds the string denoting the source_order_id field in the database.
	FieldSourceOrderID = "source_order_id"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeVipLevel holds the string denoting the vip_level edge name in mutations.
	EdgeVipLevel = "vip_level"
	// EdgeSourceOrder holds the string denoting the source_order edge name in mutations.
	EdgeSourceOrder = "source_order"
	// Table holds the table name of the uservipmembership in the database.
	Table = "user_vip_memberships"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_vip_memberships"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// VipLevelTable is the table that holds the vip_level relation/edge.
	VipLevelTable = "user_vip_memberships"
	// VipLevelInverseTable is the table name for the VIPLevel entity.
	// It exists in this package in order to avoid circular dependency with the "viplevel" package.
	VipLevelInverseTable = "vip_levels"
	// VipLevelColumn is the table column denoting the vip_level relation/edge.
	VipLevelColumn = "vip_level_id"
	// SourceOrderTable is the table that holds the source_order relation/edge.
	SourceOrderTable = "user_vip_memberships"
	// SourceOrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	SourceOrderInverseTable = "payment_orders"
	// SourceOrderColumn is the table column denoting the source_order relation/edge.
	SourceOrderColumn = "source_order_id"
)

// Columns holds all SQL columns for uservipmembership fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldVipLevelID,
	FieldStartsAt,
	FieldExpiresAt,
	FieldStatus,
	FieldSourceOrderID,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserVIPMembership queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByVipLevelID orders the results by the vip_level_id field.
func ByVipLevelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVipLevelID, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySourceOrderID orders the results by the source_order_id field.
func BySourceOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceOrderID, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByVipLevelField orders the results by vip_level field.
func ByVipLevelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVipLevelStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceOrderField orders the results by source_order field.
func BySourceOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newVipLevelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VipLevelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, VipLevelTable, VipLevelColumn),
	)
}
func newSourceOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceOrderTable, SourceOrderColumn),
	)
}
