// Code generated by ent, DO NOT EDIT.

package uservipmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldUserID, v))
}

// VipLevelID applies equality check predicate on the "vip_level_id" field. It's identical to VipLevelIDEQ.
func VipLevelID(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldVipLevelID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldStatus, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldSourceOrderID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldUserID, vs...))
}

// VipLevelIDEQ applies the EQ predicate on the "vip_level_id" field.
func VipLevelIDEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldVipLevelID, v))
}

// VipLevelIDNEQ applies the NEQ predicate on the "vip_level_id" field.
func VipLevelIDNEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldVipLevelID, v))
}

// VipLevelIDIn applies the In predicate on the "vip_level_id" field.
func VipLevelIDIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldVipLevelID, vs...))
}

// VipLevelIDNotIn applies the NotIn predicate on the "vip_level_id" field.
func VipLevelIDNotIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldVipLevelID, vs...))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldContainsFold(FieldStatus, v))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotNull(FieldSourceOrderID))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVipLevel applies the HasEdge predicate on the "vip_level" edge.
func HasVipLevel() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VipLevelTable, VipLevelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVipLevelWith applies the HasEdge predicate on the "vip_level" edge with a given conditions (other predicates).
func HasVipLevelWith(preds ...predicate.VIPLevel) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := newVipLevelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceOrder applies the HasEdge predicate on the "source_order" edge.
func HasSourceOrder() predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceOrderTable, SourceOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceOrderWith applies the HasEdge predicate on the "source_order" edge with a given conditions (other predicates).
func HasSourceOrderWith(preds ...predicate.PaymentOrder) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(func(s *sql.Selector) {
		step := newSourceOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserVIPMembership) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserVIPMembership) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserVIPMembership) predicate.UserVIPMembership {
	return predicate.UserVIPMembership(sql.NotPredicates(p))
}
