// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaidualattempt"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIDualAttemptDelete is the builder for deleting a OpenAIDualAttempt entity.
type OpenAIDualAttemptDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIDualAttemptMutation
}

// Where appends a list predicates to the OpenAIDualAttemptDelete builder.
func (_d *OpenAIDualAttemptDelete) Where(ps ...predicate.OpenAIDualAttempt) *OpenAIDualAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIDualAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIDualAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIDualAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaidualattempt.Table, sqlgraph.NewFieldSpec(openaidualattempt.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIDualAttemptDeleteOne is the builder for deleting a single OpenAIDualAttempt entity.
type OpenAIDualAttemptDeleteOne struct {
	_d *OpenAIDualAttemptDelete
}

// Where appends a list predicates to the OpenAIDualAttemptDelete builder.
func (_d *OpenAIDualAttemptDeleteOne) Where(ps ...predicate.OpenAIDualAttempt) *OpenAIDualAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIDualAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaidualattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIDualAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
