// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaidualattempt"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIDualAttemptUpdate is the builder for updating OpenAIDualAttempt entities.
type OpenAIDualAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIDualAttemptMutation
}

// Where appends a list predicates to the OpenAIDualAttemptUpdate builder.
func (_u *OpenAIDualAttemptUpdate) Where(ps ...predicate.OpenAIDualAttempt) *OpenAIDualAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *OpenAIDualAttemptUpdate) SetRequestID(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableRequestID(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAttemptID sets the "attempt_id" field.
func (_u *OpenAIDualAttemptUpdate) SetAttemptID(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetAttemptID(v)
	return _u
}

// SetNillableAttemptID sets the "attempt_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableAttemptID(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetAttemptID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OpenAIDualAttemptUpdate) SetAPIKeyID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableAPIKeyID(v *int64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OpenAIDualAttemptUpdate) AddAPIKeyID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIDualAttemptUpdate) SetUserID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableUserID(v *int64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OpenAIDualAttemptUpdate) AddUserID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIDualAttemptUpdate) SetAccountID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableAccountID(v *int64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIDualAttemptUpdate) AddAccountID(v int64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *OpenAIDualAttemptUpdate) ClearAccountID() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *OpenAIDualAttemptUpdate) SetEndpoint(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableEndpoint(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *OpenAIDualAttemptUpdate) SetMethod(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableMethod(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *OpenAIDualAttemptUpdate) SetRole(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableRole(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *OpenAIDualAttemptUpdate) SetOutcome(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableOutcome(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *OpenAIDualAttemptUpdate) SetServiceTier(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableServiceTier(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *OpenAIDualAttemptUpdate) ClearServiceTier() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIDualAttemptUpdate) SetStatus(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableStatus(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBillingBasis sets the "billing_basis" field.
func (_u *OpenAIDualAttemptUpdate) SetBillingBasis(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetBillingBasis(v)
	return _u
}

// SetNillableBillingBasis sets the "billing_basis" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableBillingBasis(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetBillingBasis(*v)
	}
	return _u
}

// ClearBillingBasis clears the value of the "billing_basis" field.
func (_u *OpenAIDualAttemptUpdate) ClearBillingBasis() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearBillingBasis()
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *OpenAIDualAttemptUpdate) SetEstimatedCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableEstimatedCost(v *float64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *OpenAIDualAttemptUpdate) AddEstimatedCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *OpenAIDualAttemptUpdate) SetActualCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableActualCost(v *float64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *OpenAIDualAttemptUpdate) AddActualCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetBilledCost sets the "billed_cost" field.
func (_u *OpenAIDualAttemptUpdate) SetBilledCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.ResetBilledCost()
	_u.mutation.SetBilledCost(v)
	return _u
}

// SetNillableBilledCost sets the "billed_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableBilledCost(v *float64) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetBilledCost(*v)
	}
	return _u
}

// AddBilledCost adds value to the "billed_cost" field.
func (_u *OpenAIDualAttemptUpdate) AddBilledCost(v float64) *OpenAIDualAttemptUpdate {
	_u.mutation.AddBilledCost(v)
	return _u
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (_u *OpenAIDualAttemptUpdate) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptUpdate {
	_u.mutation.SetUpstreamDispatchedAt(v)
	return _u
}

// SetNillableUpstreamDispatchedAt sets the "upstream_dispatched_at" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableUpstreamDispatchedAt(v *time.Time) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetUpstreamDispatchedAt(*v)
	}
	return _u
}

// ClearUpstreamDispatchedAt clears the value of the "upstream_dispatched_at" field.
func (_u *OpenAIDualAttemptUpdate) ClearUpstreamDispatchedAt() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearUpstreamDispatchedAt()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *OpenAIDualAttemptUpdate) SetCancelReason(v string) *OpenAIDualAttemptUpdate {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdate) SetNillableCancelReason(v *string) *OpenAIDualAttemptUpdate {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *OpenAIDualAttemptUpdate) ClearCancelReason() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OpenAIDualAttemptUpdate) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OpenAIDualAttemptUpdate) ClearMetadata() *OpenAIDualAttemptUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIDualAttemptUpdate) SetUpdatedAt(v time.Time) *OpenAIDualAttemptUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAIDualAttemptMutation object of the builder.
func (_u *OpenAIDualAttemptUpdate) Mutation() *OpenAIDualAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIDualAttemptUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIDualAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIDualAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIDualAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIDualAttemptUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaidualattempt.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIDualAttemptUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := openaidualattempt.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptID(); ok {
		if err := openaidualattempt.AttemptIDValidator(v); err != nil {
			return &ValidationError{Name: "attempt_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.attempt_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := openaidualattempt.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := openaidualattempt.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := openaidualattempt.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := openaidualattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := openaidualattempt.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaidualattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingBasis(); ok {
		if err := openaidualattempt.BillingBasisValidator(v); err != nil {
			return &ValidationError{Name: "billing_basis", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.billing_basis": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CancelReason(); ok {
		if err := openaidualattempt.CancelReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancel_reason", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.cancel_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIDualAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaidualattempt.Table, openaidualattempt.Columns, sqlgraph.NewFieldSpec(openaidualattempt.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(openaidualattempt.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptID(); ok {
		_spec.SetField(openaidualattempt.FieldAttemptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(openaidualattempt.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(openaidualattempt.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(openaidualattempt.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(openaidualattempt.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaidualattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaidualattempt.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(openaidualattempt.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(openaidualattempt.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(openaidualattempt.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(openaidualattempt.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(openaidualattempt.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(openaidualattempt.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(openaidualattempt.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaidualattempt.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingBasis(); ok {
		_spec.SetField(openaidualattempt.FieldBillingBasis, field.TypeString, value)
	}
	if _u.mutation.BillingBasisCleared() {
		_spec.ClearField(openaidualattempt.FieldBillingBasis, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(openaidualattempt.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(openaidualattempt.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(openaidualattempt.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(openaidualattempt.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BilledCost(); ok {
		_spec.SetField(openaidualattempt.FieldBilledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledCost(); ok {
		_spec.AddField(openaidualattempt.FieldBilledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamDispatchedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpstreamDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamDispatchedAtCleared() {
		_spec.ClearField(openaidualattempt.FieldUpstreamDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(openaidualattempt.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(openaidualattempt.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(openaidualattempt.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(openaidualattempt.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaidualattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIDualAttemptUpdateOne is the builder for updating a single OpenAIDualAttempt entity.
type OpenAIDualAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIDualAttemptMutation
}

// SetRequestID sets the "request_id" field.
func (_u *OpenAIDualAttemptUpdateOne) SetRequestID(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableRequestID(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAttemptID sets the "attempt_id" field.
func (_u *OpenAIDualAttemptUpdateOne) SetAttemptID(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetAttemptID(v)
	return _u
}

// SetNillableAttemptID sets the "attempt_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableAttemptID(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetAttemptID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *OpenAIDualAttemptUpdateOne) SetAPIKeyID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableAPIKeyID(v *int64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *OpenAIDualAttemptUpdateOne) AddAPIKeyID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIDualAttemptUpdateOne) SetUserID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableUserID(v *int64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OpenAIDualAttemptUpdateOne) AddUserID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIDualAttemptUpdateOne) SetAccountID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableAccountID(v *int64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIDualAttemptUpdateOne) AddAccountID(v int64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearAccountID() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *OpenAIDualAttemptUpdateOne) SetEndpoint(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableEndpoint(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *OpenAIDualAttemptUpdateOne) SetMethod(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableMethod(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *OpenAIDualAttemptUpdateOne) SetRole(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableRole(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *OpenAIDualAttemptUpdateOne) SetOutcome(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableOutcome(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *OpenAIDualAttemptUpdateOne) SetServiceTier(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableServiceTier(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearServiceTier() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OpenAIDualAttemptUpdateOne) SetStatus(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableStatus(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBillingBasis sets the "billing_basis" field.
func (_u *OpenAIDualAttemptUpdateOne) SetBillingBasis(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetBillingBasis(v)
	return _u
}

// SetNillableBillingBasis sets the "billing_basis" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableBillingBasis(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetBillingBasis(*v)
	}
	return _u
}

// ClearBillingBasis clears the value of the "billing_basis" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearBillingBasis() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearBillingBasis()
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) SetEstimatedCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableEstimatedCost(v *float64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) AddEstimatedCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) SetActualCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableActualCost(v *float64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) AddActualCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetBilledCost sets the "billed_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) SetBilledCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.ResetBilledCost()
	_u.mutation.SetBilledCost(v)
	return _u
}

// SetNillableBilledCost sets the "billed_cost" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableBilledCost(v *float64) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetBilledCost(*v)
	}
	return _u
}

// AddBilledCost adds value to the "billed_cost" field.
func (_u *OpenAIDualAttemptUpdateOne) AddBilledCost(v float64) *OpenAIDualAttemptUpdateOne {
	_u.mutation.AddBilledCost(v)
	return _u
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (_u *OpenAIDualAttemptUpdateOne) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetUpstreamDispatchedAt(v)
	return _u
}

// SetNillableUpstreamDispatchedAt sets the "upstream_dispatched_at" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableUpstreamDispatchedAt(v *time.Time) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetUpstreamDispatchedAt(*v)
	}
	return _u
}

// ClearUpstreamDispatchedAt clears the value of the "upstream_dispatched_at" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearUpstreamDispatchedAt() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearUpstreamDispatchedAt()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *OpenAIDualAttemptUpdateOne) SetCancelReason(v string) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *OpenAIDualAttemptUpdateOne) SetNillableCancelReason(v *string) *OpenAIDualAttemptUpdateOne {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearCancelReason() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *OpenAIDualAttemptUpdateOne) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *OpenAIDualAttemptUpdateOne) ClearMetadata() *OpenAIDualAttemptUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIDualAttemptUpdateOne) SetUpdatedAt(v time.Time) *OpenAIDualAttemptUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAIDualAttemptMutation object of the builder.
func (_u *OpenAIDualAttemptUpdateOne) Mutation() *OpenAIDualAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIDualAttemptUpdate builder.
func (_u *OpenAIDualAttemptUpdateOne) Where(ps ...predicate.OpenAIDualAttempt) *OpenAIDualAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIDualAttemptUpdateOne) Select(field string, fields ...string) *OpenAIDualAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIDualAttempt entity.
func (_u *OpenAIDualAttemptUpdateOne) Save(ctx context.Context) (*OpenAIDualAttempt, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIDualAttemptUpdateOne) SaveX(ctx context.Context) *OpenAIDualAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIDualAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIDualAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIDualAttemptUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaidualattempt.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIDualAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := openaidualattempt.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptID(); ok {
		if err := openaidualattempt.AttemptIDValidator(v); err != nil {
			return &ValidationError{Name: "attempt_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.attempt_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Endpoint(); ok {
		if err := openaidualattempt.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := openaidualattempt.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := openaidualattempt.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := openaidualattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ServiceTier(); ok {
		if err := openaidualattempt.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.service_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := openaidualattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingBasis(); ok {
		if err := openaidualattempt.BillingBasisValidator(v); err != nil {
			return &ValidationError{Name: "billing_basis", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.billing_basis": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CancelReason(); ok {
		if err := openaidualattempt.CancelReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancel_reason", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.cancel_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *OpenAIDualAttemptUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIDualAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaidualattempt.Table, openaidualattempt.Columns, sqlgraph.NewFieldSpec(openaidualattempt.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIDualAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaidualattempt.FieldID)
		for _, f := range fields {
			if !openaidualattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaidualattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(openaidualattempt.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptID(); ok {
		_spec.SetField(openaidualattempt.FieldAttemptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(openaidualattempt.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(openaidualattempt.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(openaidualattempt.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(openaidualattempt.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaidualattempt.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaidualattempt.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(openaidualattempt.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(openaidualattempt.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(openaidualattempt.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(openaidualattempt.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(openaidualattempt.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(openaidualattempt.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(openaidualattempt.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(openaidualattempt.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingBasis(); ok {
		_spec.SetField(openaidualattempt.FieldBillingBasis, field.TypeString, value)
	}
	if _u.mutation.BillingBasisCleared() {
		_spec.ClearField(openaidualattempt.FieldBillingBasis, field.TypeString)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(openaidualattempt.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(openaidualattempt.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(openaidualattempt.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(openaidualattempt.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BilledCost(); ok {
		_spec.SetField(openaidualattempt.FieldBilledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBilledCost(); ok {
		_spec.AddField(openaidualattempt.FieldBilledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpstreamDispatchedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpstreamDispatchedAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamDispatchedAtCleared() {
		_spec.ClearField(openaidualattempt.FieldUpstreamDispatchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(openaidualattempt.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(openaidualattempt.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(openaidualattempt.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(openaidualattempt.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OpenAIDualAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaidualattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
