// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaidualattempt"
)

// OpenAIDualAttemptCreate is the builder for creating a OpenAIDualAttempt entity.
type OpenAIDualAttemptCreate struct {
	config
	mutation *OpenAIDualAttemptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *OpenAIDualAttemptCreate) SetRequestID(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetAttemptID sets the "attempt_id" field.
func (_c *OpenAIDualAttemptCreate) SetAttemptID(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetAttemptID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *OpenAIDualAttemptCreate) SetAPIKeyID(v int64) *OpenAIDualAttemptCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OpenAIDualAttemptCreate) SetUserID(v int64) *OpenAIDualAttemptCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIDualAttemptCreate) SetAccountID(v int64) *OpenAIDualAttemptCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableAccountID(v *int64) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *OpenAIDualAttemptCreate) SetEndpoint(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *OpenAIDualAttemptCreate) SetMethod(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableMethod(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *OpenAIDualAttemptCreate) SetRole(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *OpenAIDualAttemptCreate) SetOutcome(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableOutcome(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetOutcome(*v)
	}
	return _c
}

// SetServiceTier sets the "service_tier" field.
func (_c *OpenAIDualAttemptCreate) SetServiceTier(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetServiceTier(v)
	return _c
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableServiceTier(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetServiceTier(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OpenAIDualAttemptCreate) SetStatus(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableStatus(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetBillingBasis sets the "billing_basis" field.
func (_c *OpenAIDualAttemptCreate) SetBillingBasis(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetBillingBasis(v)
	return _c
}

// SetNillableBillingBasis sets the "billing_basis" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableBillingBasis(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetBillingBasis(*v)
	}
	return _c
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_c *OpenAIDualAttemptCreate) SetEstimatedCost(v float64) *OpenAIDualAttemptCreate {
	_c.mutation.SetEstimatedCost(v)
	return _c
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableEstimatedCost(v *float64) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetEstimatedCost(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *OpenAIDualAttemptCreate) SetActualCost(v float64) *OpenAIDualAttemptCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableActualCost(v *float64) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetBilledCost sets the "billed_cost" field.
func (_c *OpenAIDualAttemptCreate) SetBilledCost(v float64) *OpenAIDualAttemptCreate {
	_c.mutation.SetBilledCost(v)
	return _c
}

// SetNillableBilledCost sets the "billed_cost" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableBilledCost(v *float64) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetBilledCost(*v)
	}
	return _c
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (_c *OpenAIDualAttemptCreate) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptCreate {
	_c.mutation.SetUpstreamDispatchedAt(v)
	return _c
}

// SetNillableUpstreamDispatchedAt sets the "upstream_dispatched_at" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableUpstreamDispatchedAt(v *time.Time) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetUpstreamDispatchedAt(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *OpenAIDualAttemptCreate) SetCancelReason(v string) *OpenAIDualAttemptCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableCancelReason(v *string) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *OpenAIDualAttemptCreate) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIDualAttemptCreate) SetCreatedAt(v time.Time) *OpenAIDualAttemptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableCreatedAt(v *time.Time) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIDualAttemptCreate) SetUpdatedAt(v time.Time) *OpenAIDualAttemptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIDualAttemptCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIDualAttemptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OpenAIDualAttemptMutation object of the builder.
func (_c *OpenAIDualAttemptCreate) Mutation() *OpenAIDualAttemptMutation {
	return _c.mutation
}

// Save creates the OpenAIDualAttempt in the database.
func (_c *OpenAIDualAttemptCreate) Save(ctx context.Context) (*OpenAIDualAttempt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIDualAttemptCreate) SaveX(ctx context.Context) *OpenAIDualAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIDualAttemptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIDualAttemptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIDualAttemptCreate) defaults() {
	if _, ok := _c.mutation.Method(); !ok {
		v := openaidualattempt.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		v := openaidualattempt.DefaultOutcome
		_c.mutation.SetOutcome(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := openaidualattempt.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.EstimatedCost(); !ok {
		v := openaidualattempt.DefaultEstimatedCost
		_c.mutation.SetEstimatedCost(v)
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		v := openaidualattempt.DefaultActualCost
		_c.mutation.SetActualCost(v)
	}
	if _, ok := _c.mutation.BilledCost(); !ok {
		v := openaidualattempt.DefaultBilledCost
		_c.mutation.SetBilledCost(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaidualattempt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaidualattempt.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIDualAttemptCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "OpenAIDualAttempt.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := openaidualattempt.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptID(); !ok {
		return &ValidationError{Name: "attempt_id", err: errors.New(`ent: missing required field "OpenAIDualAttempt.attempt_id"`)}
	}
	if v, ok := _c.mutation.AttemptID(); ok {
		if err := openaidualattempt.AttemptIDValidator(v); err != nil {
			return &ValidationError{Name: "attempt_id", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.attempt_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "OpenAIDualAttempt.api_key_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OpenAIDualAttempt.user_id"`)}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "OpenAIDualAttempt.endpoint"`)}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := openaidualattempt.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "OpenAIDualAttempt.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := openaidualattempt.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OpenAIDualAttempt.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := openaidualattempt.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "OpenAIDualAttempt.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := openaidualattempt.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.outcome": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ServiceTier(); ok {
		if err := openaidualattempt.ServiceTierValidator(v); err != nil {
			return &ValidationError{Name: "service_tier", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.service_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OpenAIDualAttempt.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := openaidualattempt.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BillingBasis(); ok {
		if err := openaidualattempt.BillingBasisValidator(v); err != nil {
			return &ValidationError{Name: "billing_basis", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.billing_basis": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EstimatedCost(); !ok {
		return &ValidationError{Name: "estimated_cost", err: errors.New(`ent: missing required field "OpenAIDualAttempt.estimated_cost"`)}
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		return &ValidationError{Name: "actual_cost", err: errors.New(`ent: missing required field "OpenAIDualAttempt.actual_cost"`)}
	}
	if _, ok := _c.mutation.BilledCost(); !ok {
		return &ValidationError{Name: "billed_cost", err: errors.New(`ent: missing required field "OpenAIDualAttempt.billed_cost"`)}
	}
	if v, ok := _c.mutation.CancelReason(); ok {
		if err := openaidualattempt.CancelReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancel_reason", err: fmt.Errorf(`ent: validator failed for field "OpenAIDualAttempt.cancel_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIDualAttempt.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIDualAttempt.updated_at"`)}
	}
	return nil
}

func (_c *OpenAIDualAttemptCreate) sqlSave(ctx context.Context) (*OpenAIDualAttempt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIDualAttemptCreate) createSpec() (*OpenAIDualAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIDualAttempt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaidualattempt.Table, sqlgraph.NewFieldSpec(openaidualattempt.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(openaidualattempt.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.AttemptID(); ok {
		_spec.SetField(openaidualattempt.FieldAttemptID, field.TypeString, value)
		_node.AttemptID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(openaidualattempt.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(openaidualattempt.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaidualattempt.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(openaidualattempt.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(openaidualattempt.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(openaidualattempt.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(openaidualattempt.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.ServiceTier(); ok {
		_spec.SetField(openaidualattempt.FieldServiceTier, field.TypeString, value)
		_node.ServiceTier = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(openaidualattempt.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.BillingBasis(); ok {
		_spec.SetField(openaidualattempt.FieldBillingBasis, field.TypeString, value)
		_node.BillingBasis = &value
	}
	if value, ok := _c.mutation.EstimatedCost(); ok {
		_spec.SetField(openaidualattempt.FieldEstimatedCost, field.TypeFloat64, value)
		_node.EstimatedCost = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(openaidualattempt.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = value
	}
	if value, ok := _c.mutation.BilledCost(); ok {
		_spec.SetField(openaidualattempt.FieldBilledCost, field.TypeFloat64, value)
		_node.BilledCost = value
	}
	if value, ok := _c.mutation.UpstreamDispatchedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpstreamDispatchedAt, field.TypeTime, value)
		_node.UpstreamDispatchedAt = &value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(openaidualattempt.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(openaidualattempt.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaidualattempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaidualattempt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIDualAttempt.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIDualAttemptUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIDualAttemptCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIDualAttemptUpsertOne {
	_c.conflict = opts
	return &OpenAIDualAttemptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIDualAttemptCreate) OnConflictColumns(columns ...string) *OpenAIDualAttemptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIDualAttemptUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIDualAttemptUpsertOne is the builder for "upsert"-ing
	//  one OpenAIDualAttempt node.
	OpenAIDualAttemptUpsertOne struct {
		create *OpenAIDualAttemptCreate
	}

	// OpenAIDualAttemptUpsert is the "OnConflict" setter.
	OpenAIDualAttemptUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *OpenAIDualAttemptUpsert) SetRequestID(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateRequestID() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldRequestID)
	return u
}

// SetAttemptID sets the "attempt_id" field.
func (u *OpenAIDualAttemptUpsert) SetAttemptID(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldAttemptID, v)
	return u
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateAttemptID() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldAttemptID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIDualAttemptUpsert) SetAPIKeyID(v int64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateAPIKeyID() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIDualAttemptUpsert) AddAPIKeyID(v int64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldAPIKeyID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OpenAIDualAttemptUpsert) SetUserID(v int64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateUserID() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *OpenAIDualAttemptUpsert) AddUserID(v int64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldUserID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIDualAttemptUpsert) SetAccountID(v int64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateAccountID() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIDualAttemptUpsert) AddAccountID(v int64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *OpenAIDualAttemptUpsert) ClearAccountID() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldAccountID)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *OpenAIDualAttemptUpsert) SetEndpoint(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateEndpoint() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldEndpoint)
	return u
}

// SetMethod sets the "method" field.
func (u *OpenAIDualAttemptUpsert) SetMethod(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateMethod() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldMethod)
	return u
}

// SetRole sets the "role" field.
func (u *OpenAIDualAttemptUpsert) SetRole(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateRole() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldRole)
	return u
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIDualAttemptUpsert) SetOutcome(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldOutcome, v)
	return u
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateOutcome() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldOutcome)
	return u
}

// SetServiceTier sets the "service_tier" field.
func (u *OpenAIDualAttemptUpsert) SetServiceTier(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldServiceTier, v)
	return u
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateServiceTier() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldServiceTier)
	return u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *OpenAIDualAttemptUpsert) ClearServiceTier() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldServiceTier)
	return u
}

// SetStatus sets the "status" field.
func (u *OpenAIDualAttemptUpsert) SetStatus(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateStatus() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldStatus)
	return u
}

// SetBillingBasis sets the "billing_basis" field.
func (u *OpenAIDualAttemptUpsert) SetBillingBasis(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldBillingBasis, v)
	return u
}

// UpdateBillingBasis sets the "billing_basis" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateBillingBasis() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldBillingBasis)
	return u
}

// ClearBillingBasis clears the value of the "billing_basis" field.
func (u *OpenAIDualAttemptUpsert) ClearBillingBasis() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldBillingBasis)
	return u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsert) SetEstimatedCost(v float64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldEstimatedCost, v)
	return u
}

// UpdateEstimatedCost sets the "estimated_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateEstimatedCost() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldEstimatedCost)
	return u
}

// AddEstimatedCost adds v to the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsert) AddEstimatedCost(v float64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldEstimatedCost, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *OpenAIDualAttemptUpsert) SetActualCost(v float64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateActualCost() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *OpenAIDualAttemptUpsert) AddActualCost(v float64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldActualCost, v)
	return u
}

// SetBilledCost sets the "billed_cost" field.
func (u *OpenAIDualAttemptUpsert) SetBilledCost(v float64) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldBilledCost, v)
	return u
}

// UpdateBilledCost sets the "billed_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateBilledCost() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldBilledCost)
	return u
}

// AddBilledCost adds v to the "billed_cost" field.
func (u *OpenAIDualAttemptUpsert) AddBilledCost(v float64) *OpenAIDualAttemptUpsert {
	u.Add(openaidualattempt.FieldBilledCost, v)
	return u
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsert) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldUpstreamDispatchedAt, v)
	return u
}

// UpdateUpstreamDispatchedAt sets the "upstream_dispatched_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateUpstreamDispatchedAt() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldUpstreamDispatchedAt)
	return u
}

// ClearUpstreamDispatchedAt clears the value of the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsert) ClearUpstreamDispatchedAt() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldUpstreamDispatchedAt)
	return u
}

// SetCancelReason sets the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsert) SetCancelReason(v string) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldCancelReason, v)
	return u
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateCancelReason() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldCancelReason)
	return u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsert) ClearCancelReason() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldCancelReason)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *OpenAIDualAttemptUpsert) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateMetadata() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OpenAIDualAttemptUpsert) ClearMetadata() *OpenAIDualAttemptUpsert {
	u.SetNull(openaidualattempt.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIDualAttemptUpsert) SetUpdatedAt(v time.Time) *OpenAIDualAttemptUpsert {
	u.Set(openaidualattempt.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsert) UpdateUpdatedAt() *OpenAIDualAttemptUpsert {
	u.SetExcluded(openaidualattempt.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIDualAttemptUpsertOne) UpdateNewValues() *OpenAIDualAttemptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaidualattempt.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIDualAttemptUpsertOne) Ignore() *OpenAIDualAttemptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIDualAttemptUpsertOne) DoNothing() *OpenAIDualAttemptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIDualAttemptCreate.OnConflict
// documentation for more info.
func (u *OpenAIDualAttemptUpsertOne) Update(set func(*OpenAIDualAttemptUpsert)) *OpenAIDualAttemptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIDualAttemptUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *OpenAIDualAttemptUpsertOne) SetRequestID(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateRequestID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateRequestID()
	})
}

// SetAttemptID sets the "attempt_id" field.
func (u *OpenAIDualAttemptUpsertOne) SetAttemptID(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAttemptID(v)
	})
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateAttemptID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAttemptID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIDualAttemptUpsertOne) SetAPIKeyID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIDualAttemptUpsertOne) AddAPIKeyID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateAPIKeyID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OpenAIDualAttemptUpsertOne) SetUserID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OpenAIDualAttemptUpsertOne) AddUserID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateUserID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIDualAttemptUpsertOne) SetAccountID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIDualAttemptUpsertOne) AddAccountID(v int64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateAccountID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *OpenAIDualAttemptUpsertOne) ClearAccountID() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearAccountID()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *OpenAIDualAttemptUpsertOne) SetEndpoint(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateEndpoint() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateEndpoint()
	})
}

// SetMethod sets the "method" field.
func (u *OpenAIDualAttemptUpsertOne) SetMethod(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateMethod() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateMethod()
	})
}

// SetRole sets the "role" field.
func (u *OpenAIDualAttemptUpsertOne) SetRole(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateRole() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateRole()
	})
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIDualAttemptUpsertOne) SetOutcome(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateOutcome() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateOutcome()
	})
}

// SetServiceTier sets the "service_tier" field.
func (u *OpenAIDualAttemptUpsertOne) SetServiceTier(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetServiceTier(v)
	})
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateServiceTier() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateServiceTier()
	})
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *OpenAIDualAttemptUpsertOne) ClearServiceTier() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearServiceTier()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIDualAttemptUpsertOne) SetStatus(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateStatus() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateStatus()
	})
}

// SetBillingBasis sets the "billing_basis" field.
func (u *OpenAIDualAttemptUpsertOne) SetBillingBasis(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetBillingBasis(v)
	})
}

// UpdateBillingBasis sets the "billing_basis" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateBillingBasis() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateBillingBasis()
	})
}

// ClearBillingBasis clears the value of the "billing_basis" field.
func (u *OpenAIDualAttemptUpsertOne) ClearBillingBasis() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearBillingBasis()
	})
}

// SetEstimatedCost sets the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsertOne) SetEstimatedCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetEstimatedCost(v)
	})
}

// AddEstimatedCost adds v to the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsertOne) AddEstimatedCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddEstimatedCost(v)
	})
}

// UpdateEstimatedCost sets the "estimated_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateEstimatedCost() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateEstimatedCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *OpenAIDualAttemptUpsertOne) SetActualCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *OpenAIDualAttemptUpsertOne) AddActualCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateActualCost() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateActualCost()
	})
}

// SetBilledCost sets the "billed_cost" field.
func (u *OpenAIDualAttemptUpsertOne) SetBilledCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetBilledCost(v)
	})
}

// AddBilledCost adds v to the "billed_cost" field.
func (u *OpenAIDualAttemptUpsertOne) AddBilledCost(v float64) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddBilledCost(v)
	})
}

// UpdateBilledCost sets the "billed_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateBilledCost() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateBilledCost()
	})
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsertOne) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUpstreamDispatchedAt(v)
	})
}

// UpdateUpstreamDispatchedAt sets the "upstream_dispatched_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateUpstreamDispatchedAt() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUpstreamDispatchedAt()
	})
}

// ClearUpstreamDispatchedAt clears the value of the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsertOne) ClearUpstreamDispatchedAt() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearUpstreamDispatchedAt()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsertOne) SetCancelReason(v string) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateCancelReason() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsertOne) ClearCancelReason() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearCancelReason()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OpenAIDualAttemptUpsertOne) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateMetadata() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OpenAIDualAttemptUpsertOne) ClearMetadata() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIDualAttemptUpsertOne) SetUpdatedAt(v time.Time) *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertOne) UpdateUpdatedAt() *OpenAIDualAttemptUpsertOne {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIDualAttemptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIDualAttemptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIDualAttemptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIDualAttemptUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIDualAttemptUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIDualAttemptCreateBulk is the builder for creating many OpenAIDualAttempt entities in bulk.
type OpenAIDualAttemptCreateBulk struct {
	config
	err      error
	builders []*OpenAIDualAttemptCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIDualAttempt entities in the database.
func (_c *OpenAIDualAttemptCreateBulk) Save(ctx context.Context) ([]*OpenAIDualAttempt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIDualAttempt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIDualAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIDualAttemptCreateBulk) SaveX(ctx context.Context) []*OpenAIDualAttempt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIDualAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIDualAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIDualAttempt.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIDualAttemptUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIDualAttemptCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIDualAttemptUpsertBulk {
	_c.conflict = opts
	return &OpenAIDualAttemptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIDualAttemptCreateBulk) OnConflictColumns(columns ...string) *OpenAIDualAttemptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIDualAttemptUpsertBulk{
		create: _c,
	}
}

// OpenAIDualAttemptUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIDualAttempt nodes.
type OpenAIDualAttemptUpsertBulk struct {
	create *OpenAIDualAttemptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIDualAttemptUpsertBulk) UpdateNewValues() *OpenAIDualAttemptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaidualattempt.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIDualAttempt.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIDualAttemptUpsertBulk) Ignore() *OpenAIDualAttemptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIDualAttemptUpsertBulk) DoNothing() *OpenAIDualAttemptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIDualAttemptCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIDualAttemptUpsertBulk) Update(set func(*OpenAIDualAttemptUpsert)) *OpenAIDualAttemptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIDualAttemptUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *OpenAIDualAttemptUpsertBulk) SetRequestID(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateRequestID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateRequestID()
	})
}

// SetAttemptID sets the "attempt_id" field.
func (u *OpenAIDualAttemptUpsertBulk) SetAttemptID(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAttemptID(v)
	})
}

// UpdateAttemptID sets the "attempt_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateAttemptID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAttemptID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *OpenAIDualAttemptUpsertBulk) SetAPIKeyID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *OpenAIDualAttemptUpsertBulk) AddAPIKeyID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateAPIKeyID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUserID sets the "user_id" field.
func (u *OpenAIDualAttemptUpsertBulk) SetUserID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *OpenAIDualAttemptUpsertBulk) AddUserID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateUserID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIDualAttemptUpsertBulk) SetAccountID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIDualAttemptUpsertBulk) AddAccountID(v int64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateAccountID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearAccountID() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearAccountID()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *OpenAIDualAttemptUpsertBulk) SetEndpoint(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateEndpoint() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateEndpoint()
	})
}

// SetMethod sets the "method" field.
func (u *OpenAIDualAttemptUpsertBulk) SetMethod(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateMethod() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateMethod()
	})
}

// SetRole sets the "role" field.
func (u *OpenAIDualAttemptUpsertBulk) SetRole(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateRole() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateRole()
	})
}

// SetOutcome sets the "outcome" field.
func (u *OpenAIDualAttemptUpsertBulk) SetOutcome(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetOutcome(v)
	})
}

// UpdateOutcome sets the "outcome" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateOutcome() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateOutcome()
	})
}

// SetServiceTier sets the "service_tier" field.
func (u *OpenAIDualAttemptUpsertBulk) SetServiceTier(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetServiceTier(v)
	})
}

// UpdateServiceTier sets the "service_tier" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateServiceTier() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateServiceTier()
	})
}

// ClearServiceTier clears the value of the "service_tier" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearServiceTier() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearServiceTier()
	})
}

// SetStatus sets the "status" field.
func (u *OpenAIDualAttemptUpsertBulk) SetStatus(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateStatus() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateStatus()
	})
}

// SetBillingBasis sets the "billing_basis" field.
func (u *OpenAIDualAttemptUpsertBulk) SetBillingBasis(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetBillingBasis(v)
	})
}

// UpdateBillingBasis sets the "billing_basis" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateBillingBasis() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateBillingBasis()
	})
}

// ClearBillingBasis clears the value of the "billing_basis" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearBillingBasis() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearBillingBasis()
	})
}

// SetEstimatedCost sets the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) SetEstimatedCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetEstimatedCost(v)
	})
}

// AddEstimatedCost adds v to the "estimated_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) AddEstimatedCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddEstimatedCost(v)
	})
}

// UpdateEstimatedCost sets the "estimated_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateEstimatedCost() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateEstimatedCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) SetActualCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) AddActualCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateActualCost() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateActualCost()
	})
}

// SetBilledCost sets the "billed_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) SetBilledCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetBilledCost(v)
	})
}

// AddBilledCost adds v to the "billed_cost" field.
func (u *OpenAIDualAttemptUpsertBulk) AddBilledCost(v float64) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.AddBilledCost(v)
	})
}

// UpdateBilledCost sets the "billed_cost" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateBilledCost() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateBilledCost()
	})
}

// SetUpstreamDispatchedAt sets the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsertBulk) SetUpstreamDispatchedAt(v time.Time) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUpstreamDispatchedAt(v)
	})
}

// UpdateUpstreamDispatchedAt sets the "upstream_dispatched_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateUpstreamDispatchedAt() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUpstreamDispatchedAt()
	})
}

// ClearUpstreamDispatchedAt clears the value of the "upstream_dispatched_at" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearUpstreamDispatchedAt() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearUpstreamDispatchedAt()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsertBulk) SetCancelReason(v string) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateCancelReason() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearCancelReason() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearCancelReason()
	})
}

// SetMetadata sets the "metadata" field.
func (u *OpenAIDualAttemptUpsertBulk) SetMetadata(v map[string]interface{}) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateMetadata() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *OpenAIDualAttemptUpsertBulk) ClearMetadata() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.ClearMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIDualAttemptUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIDualAttemptUpsertBulk) UpdateUpdatedAt() *OpenAIDualAttemptUpsertBulk {
	return u.Update(func(s *OpenAIDualAttemptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIDualAttemptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIDualAttemptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIDualAttemptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIDualAttemptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
