// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaidualattempt"
)

// OpenAIDualAttempt is the model entity for the OpenAIDualAttempt schema.
type OpenAIDualAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// AttemptID holds the value of the "attempt_id" field.
	AttemptID string `json:"attempt_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome string `json:"outcome,omitempty"`
	// ServiceTier holds the value of the "service_tier" field.
	ServiceTier *string `json:"service_tier,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// BillingBasis holds the value of the "billing_basis" field.
	BillingBasis *string `json:"billing_basis,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// BilledCost holds the value of the "billed_cost" field.
	BilledCost float64 `json:"billed_cost,omitempty"`
	// UpstreamDispatchedAt holds the value of the "upstream_dispatched_at" field.
	UpstreamDispatchedAt *time.Time `json:"upstream_dispatched_at,omitempty"`
	// CancelReason holds the value of the "cancel_reason" field.
	CancelReason *string `json:"cancel_reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIDualAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaidualattempt.FieldMetadata:
			values[i] = new([]byte)
		case openaidualattempt.FieldEstimatedCost, openaidualattempt.FieldActualCost, openaidualattempt.FieldBilledCost:
			values[i] = new(sql.NullFloat64)
		case openaidualattempt.FieldID, openaidualattempt.FieldAPIKeyID, openaidualattempt.FieldUserID, openaidualattempt.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case openaidualattempt.FieldRequestID, openaidualattempt.FieldAttemptID, openaidualattempt.FieldEndpoint, openaidualattempt.FieldMethod, openaidualattempt.FieldRole, openaidualattempt.FieldOutcome, openaidualattempt.FieldServiceTier, openaidualattempt.FieldStatus, openaidualattempt.FieldBillingBasis, openaidualattempt.FieldCancelReason:
			values[i] = new(sql.NullString)
		case openaidualattempt.FieldUpstreamDispatchedAt, openaidualattempt.FieldCreatedAt, openaidualattempt.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIDualAttempt fields.
func (_m *OpenAIDualAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaidualattempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaidualattempt.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case openaidualattempt.FieldAttemptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_id", values[i])
			} else if value.Valid {
				_m.AttemptID = value.String
			}
		case openaidualattempt.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case openaidualattempt.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case openaidualattempt.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case openaidualattempt.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case openaidualattempt.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case openaidualattempt.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case openaidualattempt.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = value.String
			}
		case openaidualattempt.FieldServiceTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_tier", values[i])
			} else if value.Valid {
				_m.ServiceTier = new(string)
				*_m.ServiceTier = value.String
			}
		case openaidualattempt.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case openaidualattempt.FieldBillingBasis:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_basis", values[i])
			} else if value.Valid {
				_m.BillingBasis = new(string)
				*_m.BillingBasis = value.String
			}
		case openaidualattempt.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case openaidualattempt.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case openaidualattempt.FieldBilledCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field billed_cost", values[i])
			} else if value.Valid {
				_m.BilledCost = value.Float64
			}
		case openaidualattempt.FieldUpstreamDispatchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_dispatched_at", values[i])
			} else if value.Valid {
				_m.UpstreamDispatchedAt = new(time.Time)
				*_m.UpstreamDispatchedAt = value.Time
			}
		case openaidualattempt.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				_m.CancelReason = new(string)
				*_m.CancelReason = value.String
			}
		case openaidualattempt.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case openaidualattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaidualattempt.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIDualAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIDualAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIDualAttempt.
// Note that you need to call OpenAIDualAttempt.Unwrap() before calling this method if this OpenAIDualAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIDualAttempt) Update() *OpenAIDualAttemptUpdateOne {
	return NewOpenAIDualAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIDualAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIDualAttempt) Unwrap() *OpenAIDualAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIDualAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIDualAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIDualAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("attempt_id=")
	builder.WriteString(_m.AttemptID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(_m.Outcome)
	builder.WriteString(", ")
	if v := _m.ServiceTier; v != nil {
		builder.WriteString("service_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.BillingBasis; v != nil {
		builder.WriteString("billing_basis=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("billed_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.BilledCost))
	builder.WriteString(", ")
	if v := _m.UpstreamDispatchedAt; v != nil {
		builder.WriteString("upstream_dispatched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelReason; v != nil {
		builder.WriteString("cancel_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIDualAttempts is a parsable slice of OpenAIDualAttempt.
type OpenAIDualAttempts []*OpenAIDualAttempt
