// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
)

// UserVIPMembershipDelete is the builder for deleting a UserVIPMembership entity.
type UserVIPMembershipDelete struct {
	config
	hooks    []Hook
	mutation *UserVIPMembershipMutation
}

// Where appends a list predicates to the UserVIPMembershipDelete builder.
func (_d *UserVIPMembershipDelete) Where(ps ...predicate.UserVIPMembership) *UserVIPMembershipDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserVIPMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserVIPMembershipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserVIPMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(uservipmembership.Table, sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserVIPMembershipDeleteOne is the builder for deleting a single UserVIPMembership entity.
type UserVIPMembershipDeleteOne struct {
	_d *UserVIPMembershipDelete
}

// Where appends a list predicates to the UserVIPMembershipDelete builder.
func (_d *UserVIPMembershipDeleteOne) Where(ps ...predicate.UserVIPMembership) *UserVIPMembershipDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserVIPMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uservipmembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserVIPMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
