// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// UserVIPMembership is the model entity for the UserVIPMembership schema.
type UserVIPMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// VipLevelID holds the value of the "vip_level_id" field.
	VipLevelID int64 `json:"vip_level_id,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserVIPMembershipQuery when eager-loading is set.
	Edges        UserVIPMembershipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserVIPMembershipEdges holds the relations/edges for other nodes in the graph.
type UserVIPMembershipEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// VipLevel holds the value of the vip_level edge.
	VipLevel *VIPLevel `json:"vip_level,omitempty"`
	// SourceOrder holds the value of the source_order edge.
	SourceOrder *PaymentOrder `json:"source_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserVIPMembershipEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// VipLevelOrErr returns the VipLevel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserVIPMembershipEdges) VipLevelOrErr() (*VIPLevel, error) {
	if e.VipLevel != nil {
		return e.VipLevel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: viplevel.Label}
	}
	return nil, &NotLoadedError{edge: "vip_level"}
}

// SourceOrderOrErr returns the SourceOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserVIPMembershipEdges) SourceOrderOrErr() (*PaymentOrder, error) {
	if e.SourceOrder != nil {
		return e.SourceOrder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "source_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserVIPMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uservipmembership.FieldID, uservipmembership.FieldUserID, uservipmembership.FieldVipLevelID, uservipmembership.FieldSourceOrderID:
			values[i] = new(sql.NullInt64)
		case uservipmembership.FieldStatus, uservipmembership.FieldNotes:
			values[i] = new(sql.NullString)
		case uservipmembership.FieldStartsAt, uservipmembership.FieldExpiresAt, uservipmembership.FieldCreatedAt, uservipmembership.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserVIPMembership fields.
func (_m *UserVIPMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uservipmembership.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case uservipmembership.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case uservipmembership.FieldVipLevelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vip_level_id", values[i])
			} else if value.Valid {
				_m.VipLevelID = value.Int64
			}
		case uservipmembership.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case uservipmembership.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case uservipmembership.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case uservipmembership.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case uservipmembership.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case uservipmembership.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uservipmembership.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserVIPMembership.
// This includes values selected through modifiers, order, etc.
func (_m *UserVIPMembership) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserVIPMembership entity.
func (_m *UserVIPMembership) QueryUser() *UserQuery {
	return NewUserVIPMembershipClient(_m.config).QueryUser(_m)
}

// QueryVipLevel queries the "vip_level" edge of the UserVIPMembership entity.
func (_m *UserVIPMembership) QueryVipLevel() *VIPLevelQuery {
	return NewUserVIPMembershipClient(_m.config).QueryVipLevel(_m)
}

// QuerySourceOrder queries the "source_order" edge of the UserVIPMembership entity.
func (_m *UserVIPMembership) QuerySourceOrder() *PaymentOrderQuery {
	return NewUserVIPMembershipClient(_m.config).QuerySourceOrder(_m)
}

// Update returns a builder for updating this UserVIPMembership.
// Note that you need to call UserVIPMembership.Unwrap() before calling this method if this UserVIPMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserVIPMembership) Update() *UserVIPMembershipUpdateOne {
	return NewUserVIPMembershipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserVIPMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserVIPMembership) Unwrap() *UserVIPMembership {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserVIPMembership is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserVIPMembership) String() string {
	var builder strings.Builder
	builder.WriteString("UserVIPMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("vip_level_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VipLevelID))
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserVIPMemberships is a parsable slice of UserVIPMembership.
type UserVIPMemberships []*UserVIPMembership
