// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// UserVIPMembershipUpdate is the builder for updating UserVIPMembership entities.
type UserVIPMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *UserVIPMembershipMutation
}

// Where appends a list predicates to the UserVIPMembershipUpdate builder.
func (_u *UserVIPMembershipUpdate) Where(ps ...predicate.UserVIPMembership) *UserVIPMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserVIPMembershipUpdate) SetUserID(v int64) *UserVIPMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableUserID(v *int64) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetVipLevelID sets the "vip_level_id" field.
func (_u *UserVIPMembershipUpdate) SetVipLevelID(v int64) *UserVIPMembershipUpdate {
	_u.mutation.SetVipLevelID(v)
	return _u
}

// SetNillableVipLevelID sets the "vip_level_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableVipLevelID(v *int64) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetVipLevelID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserVIPMembershipUpdate) SetStartsAt(v time.Time) *UserVIPMembershipUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableStartsAt(v *time.Time) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserVIPMembershipUpdate) SetExpiresAt(v time.Time) *UserVIPMembershipUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableExpiresAt(v *time.Time) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserVIPMembershipUpdate) SetStatus(v string) *UserVIPMembershipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableStatus(v *string) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserVIPMembershipUpdate) SetSourceOrderID(v int64) *UserVIPMembershipUpdate {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableSourceOrderID(v *int64) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserVIPMembershipUpdate) ClearSourceOrderID() *UserVIPMembershipUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserVIPMembershipUpdate) SetNotes(v string) *UserVIPMembershipUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserVIPMembershipUpdate) SetNillableNotes(v *string) *UserVIPMembershipUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserVIPMembershipUpdate) ClearNotes() *UserVIPMembershipUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserVIPMembershipUpdate) SetUpdatedAt(v time.Time) *UserVIPMembershipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVIPMembershipUpdate) SetUser(v *User) *UserVIPMembershipUpdate {
	return _u.SetUserID(v.ID)
}

// SetVipLevel sets the "vip_level" edge to the VIPLevel entity.
func (_u *UserVIPMembershipUpdate) SetVipLevel(v *VIPLevel) *UserVIPMembershipUpdate {
	return _u.SetVipLevelID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserVIPMembershipUpdate) SetSourceOrder(v *PaymentOrder) *UserVIPMembershipUpdate {
	return _u.SetSourceOrderID(v.ID)
}

// Mutation returns the UserVIPMembershipMutation object of the builder.
func (_u *UserVIPMembershipUpdate) Mutation() *UserVIPMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVIPMembershipUpdate) ClearUser() *UserVIPMembershipUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearVipLevel clears the "vip_level" edge to the VIPLevel entity.
func (_u *UserVIPMembershipUpdate) ClearVipLevel() *UserVIPMembershipUpdate {
	_u.mutation.ClearVipLevel()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserVIPMembershipUpdate) ClearSourceOrder() *UserVIPMembershipUpdate {
	_u.mutation.ClearSourceOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserVIPMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVIPMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserVIPMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVIPMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserVIPMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uservipmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVIPMembershipUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := uservipmembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserVIPMembership.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVIPMembership.user"`)
	}
	if _u.mutation.VipLevelCleared() && len(_u.mutation.VipLevelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVIPMembership.vip_level"`)
	}
	return nil
}

func (_u *UserVIPMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservipmembership.Table, uservipmembership.Columns, sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(uservipmembership.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uservipmembership.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uservipmembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(uservipmembership.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(uservipmembership.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uservipmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.UserTable,
			Columns: []string{uservipmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.UserTable,
			Columns: []string{uservipmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VipLevelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.VipLevelTable,
			Columns: []string{uservipmembership.VipLevelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VipLevelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.VipLevelTable,
			Columns: []string{uservipmembership.VipLevelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.SourceOrderTable,
			Columns: []string{uservipmembership.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.SourceOrderTable,
			Columns: []string{uservipmembership.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservipmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserVIPMembershipUpdateOne is the builder for updating a single UserVIPMembership entity.
type UserVIPMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserVIPMembershipMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserVIPMembershipUpdateOne) SetUserID(v int64) *UserVIPMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableUserID(v *int64) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetVipLevelID sets the "vip_level_id" field.
func (_u *UserVIPMembershipUpdateOne) SetVipLevelID(v int64) *UserVIPMembershipUpdateOne {
	_u.mutation.SetVipLevelID(v)
	return _u
}

// SetNillableVipLevelID sets the "vip_level_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableVipLevelID(v *int64) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetVipLevelID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserVIPMembershipUpdateOne) SetStartsAt(v time.Time) *UserVIPMembershipUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableStartsAt(v *time.Time) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserVIPMembershipUpdateOne) SetExpiresAt(v time.Time) *UserVIPMembershipUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableExpiresAt(v *time.Time) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserVIPMembershipUpdateOne) SetStatus(v string) *UserVIPMembershipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableStatus(v *string) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserVIPMembershipUpdateOne) SetSourceOrderID(v int64) *UserVIPMembershipUpdateOne {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableSourceOrderID(v *int64) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserVIPMembershipUpdateOne) ClearSourceOrderID() *UserVIPMembershipUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserVIPMembershipUpdateOne) SetNotes(v string) *UserVIPMembershipUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserVIPMembershipUpdateOne) SetNillableNotes(v *string) *UserVIPMembershipUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserVIPMembershipUpdateOne) ClearNotes() *UserVIPMembershipUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserVIPMembershipUpdateOne) SetUpdatedAt(v time.Time) *UserVIPMembershipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserVIPMembershipUpdateOne) SetUser(v *User) *UserVIPMembershipUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetVipLevel sets the "vip_level" edge to the VIPLevel entity.
func (_u *UserVIPMembershipUpdateOne) SetVipLevel(v *VIPLevel) *UserVIPMembershipUpdateOne {
	return _u.SetVipLevelID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserVIPMembershipUpdateOne) SetSourceOrder(v *PaymentOrder) *UserVIPMembershipUpdateOne {
	return _u.SetSourceOrderID(v.ID)
}

// Mutation returns the UserVIPMembershipMutation object of the builder.
func (_u *UserVIPMembershipUpdateOne) Mutation() *UserVIPMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserVIPMembershipUpdateOne) ClearUser() *UserVIPMembershipUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearVipLevel clears the "vip_level" edge to the VIPLevel entity.
func (_u *UserVIPMembershipUpdateOne) ClearVipLevel() *UserVIPMembershipUpdateOne {
	_u.mutation.ClearVipLevel()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserVIPMembershipUpdateOne) ClearSourceOrder() *UserVIPMembershipUpdateOne {
	_u.mutation.ClearSourceOrder()
	return _u
}

// Where appends a list predicates to the UserVIPMembershipUpdate builder.
func (_u *UserVIPMembershipUpdateOne) Where(ps ...predicate.UserVIPMembership) *UserVIPMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserVIPMembershipUpdateOne) Select(field string, fields ...string) *UserVIPMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserVIPMembership entity.
func (_u *UserVIPMembershipUpdateOne) Save(ctx context.Context) (*UserVIPMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserVIPMembershipUpdateOne) SaveX(ctx context.Context) *UserVIPMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserVIPMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserVIPMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserVIPMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uservipmembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserVIPMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := uservipmembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserVIPMembership.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVIPMembership.user"`)
	}
	if _u.mutation.VipLevelCleared() && len(_u.mutation.VipLevelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserVIPMembership.vip_level"`)
	}
	return nil
}

func (_u *UserVIPMembershipUpdateOne) sqlSave(ctx context.Context) (_node *UserVIPMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uservipmembership.Table, uservipmembership.Columns, sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserVIPMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uservipmembership.FieldID)
		for _, f := range fields {
			if !uservipmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uservipmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(uservipmembership.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uservipmembership.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uservipmembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(uservipmembership.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(uservipmembership.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uservipmembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.UserTable,
			Columns: []string{uservipmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.UserTable,
			Columns: []string{uservipmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VipLevelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.VipLevelTable,
			Columns: []string{uservipmembership.VipLevelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VipLevelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.VipLevelTable,
			Columns: []string{uservipmembership.VipLevelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.SourceOrderTable,
			Columns: []string{uservipmembership.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.SourceOrderTable,
			Columns: []string{uservipmembership.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserVIPMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservipmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
