// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// UserVIPMembershipCreate is the builder for creating a UserVIPMembership entity.
type UserVIPMembershipCreate struct {
	config
	mutation *UserVIPMembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserVIPMembershipCreate) SetUserID(v int64) *UserVIPMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetVipLevelID sets the "vip_level_id" field.
func (_c *UserVIPMembershipCreate) SetVipLevelID(v int64) *UserVIPMembershipCreate {
	_c.mutation.SetVipLevelID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserVIPMembershipCreate) SetStartsAt(v time.Time) *UserVIPMembershipCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserVIPMembershipCreate) SetExpiresAt(v time.Time) *UserVIPMembershipCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserVIPMembershipCreate) SetStatus(v string) *UserVIPMembershipCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserVIPMembershipCreate) SetNillableStatus(v *string) *UserVIPMembershipCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *UserVIPMembershipCreate) SetSourceOrderID(v int64) *UserVIPMembershipCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *UserVIPMembershipCreate) SetNillableSourceOrderID(v *int64) *UserVIPMembershipCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserVIPMembershipCreate) SetNotes(v string) *UserVIPMembershipCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserVIPMembershipCreate) SetNillableNotes(v *string) *UserVIPMembershipCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserVIPMembershipCreate) SetCreatedAt(v time.Time) *UserVIPMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserVIPMembershipCreate) SetNillableCreatedAt(v *time.Time) *UserVIPMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserVIPMembershipCreate) SetUpdatedAt(v time.Time) *UserVIPMembershipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserVIPMembershipCreate) SetNillableUpdatedAt(v *time.Time) *UserVIPMembershipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserVIPMembershipCreate) SetUser(v *User) *UserVIPMembershipCreate {
	return _c.SetUserID(v.ID)
}

// SetVipLevel sets the "vip_level" edge to the VIPLevel entity.
func (_c *UserVIPMembershipCreate) SetVipLevel(v *VIPLevel) *UserVIPMembershipCreate {
	return _c.SetVipLevelID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_c *UserVIPMembershipCreate) SetSourceOrder(v *PaymentOrder) *UserVIPMembershipCreate {
	return _c.SetSourceOrderID(v.ID)
}

// Mutation returns the UserVIPMembershipMutation object of the builder.
func (_c *UserVIPMembershipCreate) Mutation() *UserVIPMembershipMutation {
	return _c.mutation
}

// Save creates the UserVIPMembership in the database.
func (_c *UserVIPMembershipCreate) Save(ctx context.Context) (*UserVIPMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserVIPMembershipCreate) SaveX(ctx context.Context) *UserVIPMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserVIPMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserVIPMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserVIPMembershipCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := uservipmembership.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := uservipmembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := uservipmembership.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserVIPMembershipCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserVIPMembership.user_id"`)}
	}
	if _, ok := _c.mutation.VipLevelID(); !ok {
		return &ValidationError{Name: "vip_level_id", err: errors.New(`ent: missing required field "UserVIPMembership.vip_level_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserVIPMembership.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserVIPMembership.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserVIPMembership.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := uservipmembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserVIPMembership.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserVIPMembership.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserVIPMembership.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserVIPMembership.user"`)}
	}
	if len(_c.mutation.VipLevelIDs()) == 0 {
		return &ValidationError{Name: "vip_level", err: errors.New(`ent: missing required edge "UserVIPMembership.vip_level"`)}
	}
	return nil
}

func (_c *UserVIPMembershipCreate) sqlSave(ctx context.Context) (*UserVIPMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserVIPMembershipCreate) createSpec() (*UserVIPMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &UserVIPMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uservipmembership.Table, sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(uservipmembership.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(uservipmembership.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(uservipmembership.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(uservipmembership.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(uservipmembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(uservipmembership.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.UserTable,
			Columns: []string{uservipmembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VipLevelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.VipLevelTable,
			Columns: []string{uservipmembership.VipLevelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VipLevelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   uservipmembership.SourceOrderTable,
			Columns: []string{uservipmembership.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceOrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserVIPMembership.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserVIPMembershipUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserVIPMembershipCreate) OnConflict(opts ...sql.ConflictOption) *UserVIPMembershipUpsertOne {
	_c.conflict = opts
	return &UserVIPMembershipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserVIPMembershipCreate) OnConflictColumns(columns ...string) *UserVIPMembershipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserVIPMembershipUpsertOne{
		create: _c,
	}
}

type (
	// UserVIPMembershipUpsertOne is the builder for "upsert"-ing
	//  one UserVIPMembership node.
	UserVIPMembershipUpsertOne struct {
		create *UserVIPMembershipCreate
	}

	// UserVIPMembershipUpsert is the "OnConflict" setter.
	UserVIPMembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserVIPMembershipUpsert) SetUserID(v int64) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateUserID() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldUserID)
	return u
}

// SetVipLevelID sets the "vip_level_id" field.
func (u *UserVIPMembershipUpsert) SetVipLevelID(v int64) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldVipLevelID, v)
	return u
}

// UpdateVipLevelID sets the "vip_level_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateVipLevelID() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldVipLevelID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserVIPMembershipUpsert) SetStartsAt(v time.Time) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateStartsAt() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserVIPMembershipUpsert) SetExpiresAt(v time.Time) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateExpiresAt() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserVIPMembershipUpsert) SetStatus(v string) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateStatus() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldStatus)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserVIPMembershipUpsert) SetSourceOrderID(v int64) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateSourceOrderID() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldSourceOrderID)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserVIPMembershipUpsert) ClearSourceOrderID() *UserVIPMembershipUpsert {
	u.SetNull(uservipmembership.FieldSourceOrderID)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserVIPMembershipUpsert) SetNotes(v string) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateNotes() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UserVIPMembershipUpsert) ClearNotes() *UserVIPMembershipUpsert {
	u.SetNull(uservipmembership.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserVIPMembershipUpsert) SetUpdatedAt(v time.Time) *UserVIPMembershipUpsert {
	u.Set(uservipmembership.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsert) UpdateUpdatedAt() *UserVIPMembershipUpsert {
	u.SetExcluded(uservipmembership.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserVIPMembershipUpsertOne) UpdateNewValues() *UserVIPMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(uservipmembership.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserVIPMembershipUpsertOne) Ignore() *UserVIPMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserVIPMembershipUpsertOne) DoNothing() *UserVIPMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserVIPMembershipCreate.OnConflict
// documentation for more info.
func (u *UserVIPMembershipUpsertOne) Update(set func(*UserVIPMembershipUpsert)) *UserVIPMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserVIPMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserVIPMembershipUpsertOne) SetUserID(v int64) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateUserID() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetVipLevelID sets the "vip_level_id" field.
func (u *UserVIPMembershipUpsertOne) SetVipLevelID(v int64) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetVipLevelID(v)
	})
}

// UpdateVipLevelID sets the "vip_level_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateVipLevelID() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateVipLevelID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserVIPMembershipUpsertOne) SetStartsAt(v time.Time) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateStartsAt() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserVIPMembershipUpsertOne) SetExpiresAt(v time.Time) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateExpiresAt() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserVIPMembershipUpsertOne) SetStatus(v string) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateStatus() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserVIPMembershipUpsertOne) SetSourceOrderID(v int64) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateSourceOrderID() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserVIPMembershipUpsertOne) ClearSourceOrderID() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetNotes sets the "notes" field.
func (u *UserVIPMembershipUpsertOne) SetNotes(v string) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateNotes() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserVIPMembershipUpsertOne) ClearNotes() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserVIPMembershipUpsertOne) SetUpdatedAt(v time.Time) *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertOne) UpdateUpdatedAt() *UserVIPMembershipUpsertOne {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserVIPMembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserVIPMembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserVIPMembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserVIPMembershipUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserVIPMembershipUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserVIPMembershipCreateBulk is the builder for creating many UserVIPMembership entities in bulk.
type UserVIPMembershipCreateBulk struct {
	config
	err      error
	builders []*UserVIPMembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the UserVIPMembership entities in the database.
func (_c *UserVIPMembershipCreateBulk) Save(ctx context.Context) ([]*UserVIPMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserVIPMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserVIPMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserVIPMembershipCreateBulk) SaveX(ctx context.Context) []*UserVIPMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserVIPMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserVIPMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserVIPMembership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserVIPMembershipUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserVIPMembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserVIPMembershipUpsertBulk {
	_c.conflict = opts
	return &UserVIPMembershipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserVIPMembershipCreateBulk) OnConflictColumns(columns ...string) *UserVIPMembershipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserVIPMembershipUpsertBulk{
		create: _c,
	}
}

// UserVIPMembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of UserVIPMembership nodes.
type UserVIPMembershipUpsertBulk struct {
	create *UserVIPMembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserVIPMembershipUpsertBulk) UpdateNewValues() *UserVIPMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(uservipmembership.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserVIPMembership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserVIPMembershipUpsertBulk) Ignore() *UserVIPMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserVIPMembershipUpsertBulk) DoNothing() *UserVIPMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserVIPMembershipCreateBulk.OnConflict
// documentation for more info.
func (u *UserVIPMembershipUpsertBulk) Update(set func(*UserVIPMembershipUpsert)) *UserVIPMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserVIPMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserVIPMembershipUpsertBulk) SetUserID(v int64) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateUserID() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetVipLevelID sets the "vip_level_id" field.
func (u *UserVIPMembershipUpsertBulk) SetVipLevelID(v int64) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetVipLevelID(v)
	})
}

// UpdateVipLevelID sets the "vip_level_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateVipLevelID() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateVipLevelID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserVIPMembershipUpsertBulk) SetStartsAt(v time.Time) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateStartsAt() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserVIPMembershipUpsertBulk) SetExpiresAt(v time.Time) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateExpiresAt() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserVIPMembershipUpsertBulk) SetStatus(v string) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateStatus() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserVIPMembershipUpsertBulk) SetSourceOrderID(v int64) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateSourceOrderID() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserVIPMembershipUpsertBulk) ClearSourceOrderID() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetNotes sets the "notes" field.
func (u *UserVIPMembershipUpsertBulk) SetNotes(v string) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateNotes() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserVIPMembershipUpsertBulk) ClearNotes() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserVIPMembershipUpsertBulk) SetUpdatedAt(v time.Time) *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserVIPMembershipUpsertBulk) UpdateUpdatedAt() *UserVIPMembershipUpsertBulk {
	return u.Update(func(s *UserVIPMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserVIPMembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserVIPMembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserVIPMembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserVIPMembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
