// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// VIPLevelCreate is the builder for creating a VIPLevel entity.
type VIPLevelCreate struct {
	config
	mutation *VIPLevelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *VIPLevelCreate) SetName(v string) *VIPLevelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *VIPLevelCreate) SetDescription(v string) *VIPLevelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableDescription(v *string) *VIPLevelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *VIPLevelCreate) SetPrice(v float64) *VIPLevelCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetOriginalPrice sets the "original_price" field.
func (_c *VIPLevelCreate) SetOriginalPrice(v float64) *VIPLevelCreate {
	_c.mutation.SetOriginalPrice(v)
	return _c
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableOriginalPrice(v *float64) *VIPLevelCreate {
	if v != nil {
		_c.SetOriginalPrice(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *VIPLevelCreate) SetValidityDays(v int) *VIPLevelCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableValidityDays(v *int) *VIPLevelCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (_c *VIPLevelCreate) SetDiscountMultiplier(v float64) *VIPLevelCreate {
	_c.mutation.SetDiscountMultiplier(v)
	return _c
}

// SetNillableDiscountMultiplier sets the "discount_multiplier" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableDiscountMultiplier(v *float64) *VIPLevelCreate {
	if v != nil {
		_c.SetDiscountMultiplier(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *VIPLevelCreate) SetFeatures(v string) *VIPLevelCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableFeatures(v *string) *VIPLevelCreate {
	if v != nil {
		_c.SetFeatures(*v)
	}
	return _c
}

// SetBenefits sets the "benefits" field.
func (_c *VIPLevelCreate) SetBenefits(v map[string]interface{}) *VIPLevelCreate {
	_c.mutation.SetBenefits(v)
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *VIPLevelCreate) SetForSale(v bool) *VIPLevelCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableForSale(v *bool) *VIPLevelCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *VIPLevelCreate) SetSortOrder(v int) *VIPLevelCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableSortOrder(v *int) *VIPLevelCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VIPLevelCreate) SetCreatedAt(v time.Time) *VIPLevelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableCreatedAt(v *time.Time) *VIPLevelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VIPLevelCreate) SetUpdatedAt(v time.Time) *VIPLevelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VIPLevelCreate) SetNillableUpdatedAt(v *time.Time) *VIPLevelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddMembershipIDs adds the "memberships" edge to the UserVIPMembership entity by IDs.
func (_c *VIPLevelCreate) AddMembershipIDs(ids ...int64) *VIPLevelCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the UserVIPMembership entity.
func (_c *VIPLevelCreate) AddMemberships(v ...*UserVIPMembership) *VIPLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_c *VIPLevelCreate) AddRedeemCodeIDs(ids ...int64) *VIPLevelCreate {
	_c.mutation.AddRedeemCodeIDs(ids...)
	return _c
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_c *VIPLevelCreate) AddRedeemCodes(v ...*RedeemCode) *VIPLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedeemCodeIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *VIPLevelCreate) AddUsageLogIDs(ids ...int64) *VIPLevelCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *VIPLevelCreate) AddUsageLogs(v ...*UsageLog) *VIPLevelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the VIPLevelMutation object of the builder.
func (_c *VIPLevelCreate) Mutation() *VIPLevelMutation {
	return _c.mutation
}

// Save creates the VIPLevel in the database.
func (_c *VIPLevelCreate) Save(ctx context.Context) (*VIPLevel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VIPLevelCreate) SaveX(ctx context.Context) *VIPLevel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VIPLevelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VIPLevelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VIPLevelCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := viplevel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := viplevel.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.DiscountMultiplier(); !ok {
		v := viplevel.DefaultDiscountMultiplier
		_c.mutation.SetDiscountMultiplier(v)
	}
	if _, ok := _c.mutation.Features(); !ok {
		v := viplevel.DefaultFeatures
		_c.mutation.SetFeatures(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := viplevel.DefaultForSale
		_c.mutation.SetForSale(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := viplevel.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := viplevel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := viplevel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VIPLevelCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VIPLevel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := viplevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPLevel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "VIPLevel.description"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "VIPLevel.price"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "VIPLevel.validity_days"`)}
	}
	if _, ok := _c.mutation.DiscountMultiplier(); !ok {
		return &ValidationError{Name: "discount_multiplier", err: errors.New(`ent: missing required field "VIPLevel.discount_multiplier"`)}
	}
	if _, ok := _c.mutation.Features(); !ok {
		return &ValidationError{Name: "features", err: errors.New(`ent: missing required field "VIPLevel.features"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "VIPLevel.for_sale"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "VIPLevel.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VIPLevel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VIPLevel.updated_at"`)}
	}
	return nil
}

func (_c *VIPLevelCreate) sqlSave(ctx context.Context) (*VIPLevel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VIPLevelCreate) createSpec() (*VIPLevel, *sqlgraph.CreateSpec) {
	var (
		_node = &VIPLevel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(viplevel.Table, sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(viplevel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(viplevel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(viplevel.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.OriginalPrice(); ok {
		_spec.SetField(viplevel.FieldOriginalPrice, field.TypeFloat64, value)
		_node.OriginalPrice = &value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(viplevel.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.DiscountMultiplier(); ok {
		_spec.SetField(viplevel.FieldDiscountMultiplier, field.TypeFloat64, value)
		_node.DiscountMultiplier = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(viplevel.FieldFeatures, field.TypeString, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.Benefits(); ok {
		_spec.SetField(viplevel.FieldBenefits, field.TypeJSON, value)
		_node.Benefits = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(viplevel.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(viplevel.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(viplevel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(viplevel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.RedeemCodesTable,
			Columns: []string{viplevel.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VIPLevel.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VIPLevelUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *VIPLevelCreate) OnConflict(opts ...sql.ConflictOption) *VIPLevelUpsertOne {
	_c.conflict = opts
	return &VIPLevelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VIPLevelCreate) OnConflictColumns(columns ...string) *VIPLevelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VIPLevelUpsertOne{
		create: _c,
	}
}

type (
	// VIPLevelUpsertOne is the builder for "upsert"-ing
	//  one VIPLevel node.
	VIPLevelUpsertOne struct {
		create *VIPLevelCreate
	}

	// VIPLevelUpsert is the "OnConflict" setter.
	VIPLevelUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *VIPLevelUpsert) SetName(v string) *VIPLevelUpsert {
	u.Set(viplevel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateName() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *VIPLevelUpsert) SetDescription(v string) *VIPLevelUpsert {
	u.Set(viplevel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateDescription() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldDescription)
	return u
}

// SetPrice sets the "price" field.
func (u *VIPLevelUpsert) SetPrice(v float64) *VIPLevelUpsert {
	u.Set(viplevel.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdatePrice() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *VIPLevelUpsert) AddPrice(v float64) *VIPLevelUpsert {
	u.Add(viplevel.FieldPrice, v)
	return u
}

// SetOriginalPrice sets the "original_price" field.
func (u *VIPLevelUpsert) SetOriginalPrice(v float64) *VIPLevelUpsert {
	u.Set(viplevel.FieldOriginalPrice, v)
	return u
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateOriginalPrice() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldOriginalPrice)
	return u
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *VIPLevelUpsert) AddOriginalPrice(v float64) *VIPLevelUpsert {
	u.Add(viplevel.FieldOriginalPrice, v)
	return u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *VIPLevelUpsert) ClearOriginalPrice() *VIPLevelUpsert {
	u.SetNull(viplevel.FieldOriginalPrice)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *VIPLevelUpsert) SetValidityDays(v int) *VIPLevelUpsert {
	u.Set(viplevel.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateValidityDays() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *VIPLevelUpsert) AddValidityDays(v int) *VIPLevelUpsert {
	u.Add(viplevel.FieldValidityDays, v)
	return u
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (u *VIPLevelUpsert) SetDiscountMultiplier(v float64) *VIPLevelUpsert {
	u.Set(viplevel.FieldDiscountMultiplier, v)
	return u
}

// UpdateDiscountMultiplier sets the "discount_multiplier" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateDiscountMultiplier() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldDiscountMultiplier)
	return u
}

// AddDiscountMultiplier adds v to the "discount_multiplier" field.
func (u *VIPLevelUpsert) AddDiscountMultiplier(v float64) *VIPLevelUpsert {
	u.Add(viplevel.FieldDiscountMultiplier, v)
	return u
}

// SetFeatures sets the "features" field.
func (u *VIPLevelUpsert) SetFeatures(v string) *VIPLevelUpsert {
	u.Set(viplevel.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateFeatures() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldFeatures)
	return u
}

// SetBenefits sets the "benefits" field.
func (u *VIPLevelUpsert) SetBenefits(v map[string]interface{}) *VIPLevelUpsert {
	u.Set(viplevel.FieldBenefits, v)
	return u
}

// UpdateBenefits sets the "benefits" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateBenefits() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldBenefits)
	return u
}

// ClearBenefits clears the value of the "benefits" field.
func (u *VIPLevelUpsert) ClearBenefits() *VIPLevelUpsert {
	u.SetNull(viplevel.FieldBenefits)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *VIPLevelUpsert) SetForSale(v bool) *VIPLevelUpsert {
	u.Set(viplevel.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateForSale() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldForSale)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *VIPLevelUpsert) SetSortOrder(v int) *VIPLevelUpsert {
	u.Set(viplevel.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateSortOrder() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VIPLevelUpsert) AddSortOrder(v int) *VIPLevelUpsert {
	u.Add(viplevel.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPLevelUpsert) SetUpdatedAt(v time.Time) *VIPLevelUpsert {
	u.Set(viplevel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPLevelUpsert) UpdateUpdatedAt() *VIPLevelUpsert {
	u.SetExcluded(viplevel.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VIPLevelUpsertOne) UpdateNewValues() *VIPLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(viplevel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VIPLevelUpsertOne) Ignore() *VIPLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VIPLevelUpsertOne) DoNothing() *VIPLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VIPLevelCreate.OnConflict
// documentation for more info.
func (u *VIPLevelUpsertOne) Update(set func(*VIPLevelUpsert)) *VIPLevelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VIPLevelUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *VIPLevelUpsertOne) SetName(v string) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateName() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *VIPLevelUpsertOne) SetDescription(v string) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateDescription() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *VIPLevelUpsertOne) SetPrice(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *VIPLevelUpsertOne) AddPrice(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdatePrice() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *VIPLevelUpsertOne) SetOriginalPrice(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *VIPLevelUpsertOne) AddOriginalPrice(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateOriginalPrice() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *VIPLevelUpsertOne) ClearOriginalPrice() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *VIPLevelUpsertOne) SetValidityDays(v int) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *VIPLevelUpsertOne) AddValidityDays(v int) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateValidityDays() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateValidityDays()
	})
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (u *VIPLevelUpsertOne) SetDiscountMultiplier(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetDiscountMultiplier(v)
	})
}

// AddDiscountMultiplier adds v to the "discount_multiplier" field.
func (u *VIPLevelUpsertOne) AddDiscountMultiplier(v float64) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddDiscountMultiplier(v)
	})
}

// UpdateDiscountMultiplier sets the "discount_multiplier" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateDiscountMultiplier() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateDiscountMultiplier()
	})
}

// SetFeatures sets the "features" field.
func (u *VIPLevelUpsertOne) SetFeatures(v string) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateFeatures() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateFeatures()
	})
}

// SetBenefits sets the "benefits" field.
func (u *VIPLevelUpsertOne) SetBenefits(v map[string]interface{}) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetBenefits(v)
	})
}

// UpdateBenefits sets the "benefits" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateBenefits() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateBenefits()
	})
}

// ClearBenefits clears the value of the "benefits" field.
func (u *VIPLevelUpsertOne) ClearBenefits() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.ClearBenefits()
	})
}

// SetForSale sets the "for_sale" field.
func (u *VIPLevelUpsertOne) SetForSale(v bool) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateForSale() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VIPLevelUpsertOne) SetSortOrder(v int) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VIPLevelUpsertOne) AddSortOrder(v int) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateSortOrder() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPLevelUpsertOne) SetUpdatedAt(v time.Time) *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPLevelUpsertOne) UpdateUpdatedAt() *VIPLevelUpsertOne {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VIPLevelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VIPLevelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VIPLevelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VIPLevelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VIPLevelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VIPLevelCreateBulk is the builder for creating many VIPLevel entities in bulk.
type VIPLevelCreateBulk struct {
	config
	err      error
	builders []*VIPLevelCreate
	conflict []sql.ConflictOption
}

// Save creates the VIPLevel entities in the database.
func (_c *VIPLevelCreateBulk) Save(ctx context.Context) ([]*VIPLevel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VIPLevel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VIPLevelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VIPLevelCreateBulk) SaveX(ctx context.Context) []*VIPLevel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VIPLevelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VIPLevelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VIPLevel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VIPLevelUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *VIPLevelCreateBulk) OnConflict(opts ...sql.ConflictOption) *VIPLevelUpsertBulk {
	_c.conflict = opts
	return &VIPLevelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VIPLevelCreateBulk) OnConflictColumns(columns ...string) *VIPLevelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VIPLevelUpsertBulk{
		create: _c,
	}
}

// VIPLevelUpsertBulk is the builder for "upsert"-ing
// a bulk of VIPLevel nodes.
type VIPLevelUpsertBulk struct {
	create *VIPLevelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VIPLevelUpsertBulk) UpdateNewValues() *VIPLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(viplevel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VIPLevel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VIPLevelUpsertBulk) Ignore() *VIPLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VIPLevelUpsertBulk) DoNothing() *VIPLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VIPLevelCreateBulk.OnConflict
// documentation for more info.
func (u *VIPLevelUpsertBulk) Update(set func(*VIPLevelUpsert)) *VIPLevelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VIPLevelUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *VIPLevelUpsertBulk) SetName(v string) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateName() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *VIPLevelUpsertBulk) SetDescription(v string) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateDescription() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateDescription()
	})
}

// SetPrice sets the "price" field.
func (u *VIPLevelUpsertBulk) SetPrice(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *VIPLevelUpsertBulk) AddPrice(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdatePrice() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdatePrice()
	})
}

// SetOriginalPrice sets the "original_price" field.
func (u *VIPLevelUpsertBulk) SetOriginalPrice(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetOriginalPrice(v)
	})
}

// AddOriginalPrice adds v to the "original_price" field.
func (u *VIPLevelUpsertBulk) AddOriginalPrice(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddOriginalPrice(v)
	})
}

// UpdateOriginalPrice sets the "original_price" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateOriginalPrice() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateOriginalPrice()
	})
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (u *VIPLevelUpsertBulk) ClearOriginalPrice() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.ClearOriginalPrice()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *VIPLevelUpsertBulk) SetValidityDays(v int) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *VIPLevelUpsertBulk) AddValidityDays(v int) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateValidityDays() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateValidityDays()
	})
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (u *VIPLevelUpsertBulk) SetDiscountMultiplier(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetDiscountMultiplier(v)
	})
}

// AddDiscountMultiplier adds v to the "discount_multiplier" field.
func (u *VIPLevelUpsertBulk) AddDiscountMultiplier(v float64) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddDiscountMultiplier(v)
	})
}

// UpdateDiscountMultiplier sets the "discount_multiplier" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateDiscountMultiplier() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateDiscountMultiplier()
	})
}

// SetFeatures sets the "features" field.
func (u *VIPLevelUpsertBulk) SetFeatures(v string) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateFeatures() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateFeatures()
	})
}

// SetBenefits sets the "benefits" field.
func (u *VIPLevelUpsertBulk) SetBenefits(v map[string]interface{}) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetBenefits(v)
	})
}

// UpdateBenefits sets the "benefits" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateBenefits() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateBenefits()
	})
}

// ClearBenefits clears the value of the "benefits" field.
func (u *VIPLevelUpsertBulk) ClearBenefits() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.ClearBenefits()
	})
}

// SetForSale sets the "for_sale" field.
func (u *VIPLevelUpsertBulk) SetForSale(v bool) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateForSale() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateForSale()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VIPLevelUpsertBulk) SetSortOrder(v int) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VIPLevelUpsertBulk) AddSortOrder(v int) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateSortOrder() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VIPLevelUpsertBulk) SetUpdatedAt(v time.Time) *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VIPLevelUpsertBulk) UpdateUpdatedAt() *VIPLevelUpsertBulk {
	return u.Update(func(s *VIPLevelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VIPLevelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VIPLevelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VIPLevelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VIPLevelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
