// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// VIPLevelQuery is the builder for querying VIPLevel entities.
type VIPLevelQuery struct {
	config
	ctx             *QueryContext
	order           []viplevel.OrderOption
	inters          []Interceptor
	predicates      []predicate.VIPLevel
	withMemberships *UserVIPMembershipQuery
	withRedeemCodes *RedeemCodeQuery
	withUsageLogs   *UsageLogQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VIPLevelQuery builder.
func (_q *VIPLevelQuery) Where(ps ...predicate.VIPLevel) *VIPLevelQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VIPLevelQuery) Limit(limit int) *VIPLevelQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VIPLevelQuery) Offset(offset int) *VIPLevelQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VIPLevelQuery) Unique(unique bool) *VIPLevelQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VIPLevelQuery) Order(o ...viplevel.OrderOption) *VIPLevelQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMemberships chains the current query on the "memberships" edge.
func (_q *VIPLevelQuery) QueryMemberships() *UserVIPMembershipQuery {
	query := (&UserVIPMembershipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(viplevel.Table, viplevel.FieldID, selector),
			sqlgraph.To(uservipmembership.Table, uservipmembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, viplevel.MembershipsTable, viplevel.MembershipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRedeemCodes chains the current query on the "redeem_codes" edge.
func (_q *VIPLevelQuery) QueryRedeemCodes() *RedeemCodeQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(viplevel.Table, viplevel.FieldID, selector),
			sqlgraph.To(redeemcode.Table, redeemcode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, viplevel.RedeemCodesTable, viplevel.RedeemCodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsageLogs chains the current query on the "usage_logs" edge.
func (_q *VIPLevelQuery) QueryUsageLogs() *UsageLogQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(viplevel.Table, viplevel.FieldID, selector),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, viplevel.UsageLogsTable, viplevel.UsageLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VIPLevel entity from the query.
// Returns a *NotFoundError when no VIPLevel was found.
func (_q *VIPLevelQuery) First(ctx context.Context) (*VIPLevel, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{viplevel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VIPLevelQuery) FirstX(ctx context.Context) *VIPLevel {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VIPLevel ID from the query.
// Returns a *NotFoundError when no VIPLevel ID was found.
func (_q *VIPLevelQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{viplevel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VIPLevelQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VIPLevel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VIPLevel entity is found.
// Returns a *NotFoundError when no VIPLevel entities are found.
func (_q *VIPLevelQuery) Only(ctx context.Context) (*VIPLevel, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{viplevel.Label}
	default:
		return nil, &NotSingularError{viplevel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VIPLevelQuery) OnlyX(ctx context.Context) *VIPLevel {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VIPLevel ID in the query.
// Returns a *NotSingularError when more than one VIPLevel ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VIPLevelQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{viplevel.Label}
	default:
		err = &NotSingularError{viplevel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VIPLevelQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VIPLevels.
func (_q *VIPLevelQuery) All(ctx context.Context) ([]*VIPLevel, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VIPLevel, *VIPLevelQuery]()
	return withInterceptors[[]*VIPLevel](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VIPLevelQuery) AllX(ctx context.Context) []*VIPLevel {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VIPLevel IDs.
func (_q *VIPLevelQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(viplevel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VIPLevelQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VIPLevelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VIPLevelQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VIPLevelQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VIPLevelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VIPLevelQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VIPLevelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VIPLevelQuery) Clone() *VIPLevelQuery {
	if _q == nil {
		return nil
	}
	return &VIPLevelQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]viplevel.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.VIPLevel{}, _q.predicates...),
		withMemberships: _q.withMemberships.Clone(),
		withRedeemCodes: _q.withRedeemCodes.Clone(),
		withUsageLogs:   _q.withUsageLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMemberships tells the query-builder to eager-load the nodes that are connected to
// the "memberships" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VIPLevelQuery) WithMemberships(opts ...func(*UserVIPMembershipQuery)) *VIPLevelQuery {
	query := (&UserVIPMembershipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemberships = query
	return _q
}

// WithRedeemCodes tells the query-builder to eager-load the nodes that are connected to
// the "redeem_codes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VIPLevelQuery) WithRedeemCodes(opts ...func(*RedeemCodeQuery)) *VIPLevelQuery {
	query := (&RedeemCodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRedeemCodes = query
	return _q
}

// WithUsageLogs tells the query-builder to eager-load the nodes that are connected to
// the "usage_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VIPLevelQuery) WithUsageLogs(opts ...func(*UsageLogQuery)) *VIPLevelQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsageLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VIPLevel.Query().
//		GroupBy(viplevel.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VIPLevelQuery) GroupBy(field string, fields ...string) *VIPLevelGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VIPLevelGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = viplevel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.VIPLevel.Query().
//		Select(viplevel.FieldName).
//		Scan(ctx, &v)
func (_q *VIPLevelQuery) Select(fields ...string) *VIPLevelSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VIPLevelSelect{VIPLevelQuery: _q}
	sbuild.label = viplevel.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VIPLevelSelect configured with the given aggregations.
func (_q *VIPLevelQuery) Aggregate(fns ...AggregateFunc) *VIPLevelSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VIPLevelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !viplevel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VIPLevelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VIPLevel, error) {
	var (
		nodes       = []*VIPLevel{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withMemberships != nil,
			_q.withRedeemCodes != nil,
			_q.withUsageLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VIPLevel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VIPLevel{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMemberships; query != nil {
		if err := _q.loadMemberships(ctx, query, nodes,
			func(n *VIPLevel) { n.Edges.Memberships = []*UserVIPMembership{} },
			func(n *VIPLevel, e *UserVIPMembership) { n.Edges.Memberships = append(n.Edges.Memberships, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRedeemCodes; query != nil {
		if err := _q.loadRedeemCodes(ctx, query, nodes,
			func(n *VIPLevel) { n.Edges.RedeemCodes = []*RedeemCode{} },
			func(n *VIPLevel, e *RedeemCode) { n.Edges.RedeemCodes = append(n.Edges.RedeemCodes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsageLogs; query != nil {
		if err := _q.loadUsageLogs(ctx, query, nodes,
			func(n *VIPLevel) { n.Edges.UsageLogs = []*UsageLog{} },
			func(n *VIPLevel, e *UsageLog) { n.Edges.UsageLogs = append(n.Edges.UsageLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VIPLevelQuery) loadMemberships(ctx context.Context, query *UserVIPMembershipQuery, nodes []*VIPLevel, init func(*VIPLevel), assign func(*VIPLevel, *UserVIPMembership)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*VIPLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(uservipmembership.FieldVipLevelID)
	}
	query.Where(predicate.UserVIPMembership(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(viplevel.MembershipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VipLevelID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "vip_level_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *VIPLevelQuery) loadRedeemCodes(ctx context.Context, query *RedeemCodeQuery, nodes []*VIPLevel, init func(*VIPLevel), assign func(*VIPLevel, *RedeemCode)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*VIPLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(redeemcode.FieldVipLevelID)
	}
	query.Where(predicate.RedeemCode(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(viplevel.RedeemCodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VipLevelID
		if fk == nil {
			return fmt.Errorf(`foreign-key "vip_level_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "vip_level_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *VIPLevelQuery) loadUsageLogs(ctx context.Context, query *UsageLogQuery, nodes []*VIPLevel, init func(*VIPLevel), assign func(*VIPLevel, *UsageLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*VIPLevel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagelog.FieldVipLevelID)
	}
	query.Where(predicate.UsageLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(viplevel.UsageLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VipLevelID
		if fk == nil {
			return fmt.Errorf(`foreign-key "vip_level_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "vip_level_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VIPLevelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VIPLevelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(viplevel.Table, viplevel.Columns, sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viplevel.FieldID)
		for i := range fields {
			if fields[i] != viplevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VIPLevelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(viplevel.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = viplevel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *VIPLevelQuery) ForUpdate(opts ...sql.LockOption) *VIPLevelQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *VIPLevelQuery) ForShare(opts ...sql.LockOption) *VIPLevelQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// VIPLevelGroupBy is the group-by builder for VIPLevel entities.
type VIPLevelGroupBy struct {
	selector
	build *VIPLevelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VIPLevelGroupBy) Aggregate(fns ...AggregateFunc) *VIPLevelGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VIPLevelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VIPLevelQuery, *VIPLevelGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VIPLevelGroupBy) sqlScan(ctx context.Context, root *VIPLevelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VIPLevelSelect is the builder for selecting fields of VIPLevel entities.
type VIPLevelSelect struct {
	*VIPLevelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VIPLevelSelect) Aggregate(fns ...AggregateFunc) *VIPLevelSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VIPLevelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VIPLevelQuery, *VIPLevelSelect](ctx, _s.VIPLevelQuery, _s, _s.inters, v)
}

func (_s *VIPLevelSelect) sqlScan(ctx context.Context, root *VIPLevelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
