// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/uservipmembership"
	"github.com/Wei-Shaw/sub2api/ent/viplevel"
)

// VIPLevelUpdate is the builder for updating VIPLevel entities.
type VIPLevelUpdate struct {
	config
	hooks    []Hook
	mutation *VIPLevelMutation
}

// Where appends a list predicates to the VIPLevelUpdate builder.
func (_u *VIPLevelUpdate) Where(ps ...predicate.VIPLevel) *VIPLevelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VIPLevelUpdate) SetName(v string) *VIPLevelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableName(v *string) *VIPLevelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *VIPLevelUpdate) SetDescription(v string) *VIPLevelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableDescription(v *string) *VIPLevelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *VIPLevelUpdate) SetPrice(v float64) *VIPLevelUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillablePrice(v *float64) *VIPLevelUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *VIPLevelUpdate) AddPrice(v float64) *VIPLevelUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *VIPLevelUpdate) SetOriginalPrice(v float64) *VIPLevelUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableOriginalPrice(v *float64) *VIPLevelUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *VIPLevelUpdate) AddOriginalPrice(v float64) *VIPLevelUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *VIPLevelUpdate) ClearOriginalPrice() *VIPLevelUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *VIPLevelUpdate) SetValidityDays(v int) *VIPLevelUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableValidityDays(v *int) *VIPLevelUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *VIPLevelUpdate) AddValidityDays(v int) *VIPLevelUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (_u *VIPLevelUpdate) SetDiscountMultiplier(v float64) *VIPLevelUpdate {
	_u.mutation.ResetDiscountMultiplier()
	_u.mutation.SetDiscountMultiplier(v)
	return _u
}

// SetNillableDiscountMultiplier sets the "discount_multiplier" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableDiscountMultiplier(v *float64) *VIPLevelUpdate {
	if v != nil {
		_u.SetDiscountMultiplier(*v)
	}
	return _u
}

// AddDiscountMultiplier adds value to the "discount_multiplier" field.
func (_u *VIPLevelUpdate) AddDiscountMultiplier(v float64) *VIPLevelUpdate {
	_u.mutation.AddDiscountMultiplier(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *VIPLevelUpdate) SetFeatures(v string) *VIPLevelUpdate {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableFeatures(v *string) *VIPLevelUpdate {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetBenefits sets the "benefits" field.
func (_u *VIPLevelUpdate) SetBenefits(v map[string]interface{}) *VIPLevelUpdate {
	_u.mutation.SetBenefits(v)
	return _u
}

// ClearBenefits clears the value of the "benefits" field.
func (_u *VIPLevelUpdate) ClearBenefits() *VIPLevelUpdate {
	_u.mutation.ClearBenefits()
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *VIPLevelUpdate) SetForSale(v bool) *VIPLevelUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableForSale(v *bool) *VIPLevelUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *VIPLevelUpdate) SetSortOrder(v int) *VIPLevelUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *VIPLevelUpdate) SetNillableSortOrder(v *int) *VIPLevelUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *VIPLevelUpdate) AddSortOrder(v int) *VIPLevelUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VIPLevelUpdate) SetUpdatedAt(v time.Time) *VIPLevelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the UserVIPMembership entity by IDs.
func (_u *VIPLevelUpdate) AddMembershipIDs(ids ...int64) *VIPLevelUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserVIPMembership entity.
func (_u *VIPLevelUpdate) AddMemberships(v ...*UserVIPMembership) *VIPLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *VIPLevelUpdate) AddUsageLogIDs(ids ...int64) *VIPLevelUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *VIPLevelUpdate) AddUsageLogs(v ...*UsageLog) *VIPLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the VIPLevelMutation object of the builder.
func (_u *VIPLevelUpdate) Mutation() *VIPLevelMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the UserVIPMembership entity.
func (_u *VIPLevelUpdate) ClearMemberships() *VIPLevelUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserVIPMembership entities by IDs.
func (_u *VIPLevelUpdate) RemoveMembershipIDs(ids ...int64) *VIPLevelUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserVIPMembership entities.
func (_u *VIPLevelUpdate) RemoveMemberships(v ...*UserVIPMembership) *VIPLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *VIPLevelUpdate) ClearUsageLogs() *VIPLevelUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *VIPLevelUpdate) RemoveUsageLogIDs(ids ...int64) *VIPLevelUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *VIPLevelUpdate) RemoveUsageLogs(v ...*UsageLog) *VIPLevelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VIPLevelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VIPLevelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VIPLevelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VIPLevelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VIPLevelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := viplevel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VIPLevelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := viplevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPLevel.name": %w`, err)}
		}
	}
	return nil
}

func (_u *VIPLevelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viplevel.Table, viplevel.Columns, sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(viplevel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(viplevel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(viplevel.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(viplevel.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(viplevel.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(viplevel.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(viplevel.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(viplevel.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(viplevel.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiscountMultiplier(); ok {
		_spec.SetField(viplevel.FieldDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountMultiplier(); ok {
		_spec.AddField(viplevel.FieldDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(viplevel.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.Benefits(); ok {
		_spec.SetField(viplevel.FieldBenefits, field.TypeJSON, value)
	}
	if _u.mutation.BenefitsCleared() {
		_spec.ClearField(viplevel.FieldBenefits, field.TypeJSON)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(viplevel.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(viplevel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(viplevel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(viplevel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viplevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VIPLevelUpdateOne is the builder for updating a single VIPLevel entity.
type VIPLevelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VIPLevelMutation
}

// SetName sets the "name" field.
func (_u *VIPLevelUpdateOne) SetName(v string) *VIPLevelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableName(v *string) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *VIPLevelUpdateOne) SetDescription(v string) *VIPLevelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableDescription(v *string) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *VIPLevelUpdateOne) SetPrice(v float64) *VIPLevelUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillablePrice(v *float64) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *VIPLevelUpdateOne) AddPrice(v float64) *VIPLevelUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *VIPLevelUpdateOne) SetOriginalPrice(v float64) *VIPLevelUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableOriginalPrice(v *float64) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *VIPLevelUpdateOne) AddOriginalPrice(v float64) *VIPLevelUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *VIPLevelUpdateOne) ClearOriginalPrice() *VIPLevelUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *VIPLevelUpdateOne) SetValidityDays(v int) *VIPLevelUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableValidityDays(v *int) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *VIPLevelUpdateOne) AddValidityDays(v int) *VIPLevelUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetDiscountMultiplier sets the "discount_multiplier" field.
func (_u *VIPLevelUpdateOne) SetDiscountMultiplier(v float64) *VIPLevelUpdateOne {
	_u.mutation.ResetDiscountMultiplier()
	_u.mutation.SetDiscountMultiplier(v)
	return _u
}

// SetNillableDiscountMultiplier sets the "discount_multiplier" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableDiscountMultiplier(v *float64) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetDiscountMultiplier(*v)
	}
	return _u
}

// AddDiscountMultiplier adds value to the "discount_multiplier" field.
func (_u *VIPLevelUpdateOne) AddDiscountMultiplier(v float64) *VIPLevelUpdateOne {
	_u.mutation.AddDiscountMultiplier(v)
	return _u
}

// SetFeatures sets the "features" field.
func (_u *VIPLevelUpdateOne) SetFeatures(v string) *VIPLevelUpdateOne {
	_u.mutation.SetFeatures(v)
	return _u
}

// SetNillableFeatures sets the "features" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableFeatures(v *string) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetFeatures(*v)
	}
	return _u
}

// SetBenefits sets the "benefits" field.
func (_u *VIPLevelUpdateOne) SetBenefits(v map[string]interface{}) *VIPLevelUpdateOne {
	_u.mutation.SetBenefits(v)
	return _u
}

// ClearBenefits clears the value of the "benefits" field.
func (_u *VIPLevelUpdateOne) ClearBenefits() *VIPLevelUpdateOne {
	_u.mutation.ClearBenefits()
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *VIPLevelUpdateOne) SetForSale(v bool) *VIPLevelUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableForSale(v *bool) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *VIPLevelUpdateOne) SetSortOrder(v int) *VIPLevelUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *VIPLevelUpdateOne) SetNillableSortOrder(v *int) *VIPLevelUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *VIPLevelUpdateOne) AddSortOrder(v int) *VIPLevelUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VIPLevelUpdateOne) SetUpdatedAt(v time.Time) *VIPLevelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the UserVIPMembership entity by IDs.
func (_u *VIPLevelUpdateOne) AddMembershipIDs(ids ...int64) *VIPLevelUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserVIPMembership entity.
func (_u *VIPLevelUpdateOne) AddMemberships(v ...*UserVIPMembership) *VIPLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *VIPLevelUpdateOne) AddUsageLogIDs(ids ...int64) *VIPLevelUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *VIPLevelUpdateOne) AddUsageLogs(v ...*UsageLog) *VIPLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the VIPLevelMutation object of the builder.
func (_u *VIPLevelUpdateOne) Mutation() *VIPLevelMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the UserVIPMembership entity.
func (_u *VIPLevelUpdateOne) ClearMemberships() *VIPLevelUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserVIPMembership entities by IDs.
func (_u *VIPLevelUpdateOne) RemoveMembershipIDs(ids ...int64) *VIPLevelUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserVIPMembership entities.
func (_u *VIPLevelUpdateOne) RemoveMemberships(v ...*UserVIPMembership) *VIPLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *VIPLevelUpdateOne) ClearUsageLogs() *VIPLevelUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *VIPLevelUpdateOne) RemoveUsageLogIDs(ids ...int64) *VIPLevelUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *VIPLevelUpdateOne) RemoveUsageLogs(v ...*UsageLog) *VIPLevelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the VIPLevelUpdate builder.
func (_u *VIPLevelUpdateOne) Where(ps ...predicate.VIPLevel) *VIPLevelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VIPLevelUpdateOne) Select(field string, fields ...string) *VIPLevelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VIPLevel entity.
func (_u *VIPLevelUpdateOne) Save(ctx context.Context) (*VIPLevel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VIPLevelUpdateOne) SaveX(ctx context.Context) *VIPLevel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VIPLevelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VIPLevelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VIPLevelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := viplevel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VIPLevelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := viplevel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VIPLevel.name": %w`, err)}
		}
	}
	return nil
}

func (_u *VIPLevelUpdateOne) sqlSave(ctx context.Context) (_node *VIPLevel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(viplevel.Table, viplevel.Columns, sqlgraph.NewFieldSpec(viplevel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VIPLevel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viplevel.FieldID)
		for _, f := range fields {
			if !viplevel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != viplevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(viplevel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(viplevel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(viplevel.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(viplevel.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(viplevel.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(viplevel.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(viplevel.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(viplevel.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(viplevel.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiscountMultiplier(); ok {
		_spec.SetField(viplevel.FieldDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountMultiplier(); ok {
		_spec.AddField(viplevel.FieldDiscountMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Features(); ok {
		_spec.SetField(viplevel.FieldFeatures, field.TypeString, value)
	}
	if value, ok := _u.mutation.Benefits(); ok {
		_spec.SetField(viplevel.FieldBenefits, field.TypeJSON, value)
	}
	if _u.mutation.BenefitsCleared() {
		_spec.ClearField(viplevel.FieldBenefits, field.TypeJSON)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(viplevel.FieldForSale, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(viplevel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(viplevel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(viplevel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.MembershipsTable,
			Columns: []string{viplevel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(uservipmembership.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   viplevel.UsageLogsTable,
			Columns: []string{viplevel.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VIPLevel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{viplevel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
