// Code generated by ent, DO NOT EDIT.

package viplevel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldPrice, v))
}

// OriginalPrice applies equality check predicate on the "original_price" field. It's identical to OriginalPriceEQ.
func OriginalPrice(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldOriginalPrice, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldValidityDays, v))
}

// DiscountMultiplier applies equality check predicate on the "discount_multiplier" field. It's identical to DiscountMultiplierEQ.
func DiscountMultiplier(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldDiscountMultiplier, v))
}

// Features applies equality check predicate on the "features" field. It's identical to FeaturesEQ.
func Features(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldFeatures, v))
}

// ForSale applies equality check predicate on the "for_sale" field. It's identical to ForSaleEQ.
func ForSale(v bool) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldForSale, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldPrice, v))
}

// OriginalPriceEQ applies the EQ predicate on the "original_price" field.
func OriginalPriceEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldOriginalPrice, v))
}

// OriginalPriceNEQ applies the NEQ predicate on the "original_price" field.
func OriginalPriceNEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldOriginalPrice, v))
}

// OriginalPriceIn applies the In predicate on the "original_price" field.
func OriginalPriceIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldOriginalPrice, vs...))
}

// OriginalPriceNotIn applies the NotIn predicate on the "original_price" field.
func OriginalPriceNotIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldOriginalPrice, vs...))
}

// OriginalPriceGT applies the GT predicate on the "original_price" field.
func OriginalPriceGT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldOriginalPrice, v))
}

// OriginalPriceGTE applies the GTE predicate on the "original_price" field.
func OriginalPriceGTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldOriginalPrice, v))
}

// OriginalPriceLT applies the LT predicate on the "original_price" field.
func OriginalPriceLT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldOriginalPrice, v))
}

// OriginalPriceLTE applies the LTE predicate on the "original_price" field.
func OriginalPriceLTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldOriginalPrice, v))
}

// OriginalPriceIsNil applies the IsNil predicate on the "original_price" field.
func OriginalPriceIsNil() predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIsNull(FieldOriginalPrice))
}

// OriginalPriceNotNil applies the NotNil predicate on the "original_price" field.
func OriginalPriceNotNil() predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotNull(FieldOriginalPrice))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldValidityDays, v))
}

// DiscountMultiplierEQ applies the EQ predicate on the "discount_multiplier" field.
func DiscountMultiplierEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldDiscountMultiplier, v))
}

// DiscountMultiplierNEQ applies the NEQ predicate on the "discount_multiplier" field.
func DiscountMultiplierNEQ(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldDiscountMultiplier, v))
}

// DiscountMultiplierIn applies the In predicate on the "discount_multiplier" field.
func DiscountMultiplierIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldDiscountMultiplier, vs...))
}

// DiscountMultiplierNotIn applies the NotIn predicate on the "discount_multiplier" field.
func DiscountMultiplierNotIn(vs ...float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldDiscountMultiplier, vs...))
}

// DiscountMultiplierGT applies the GT predicate on the "discount_multiplier" field.
func DiscountMultiplierGT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldDiscountMultiplier, v))
}

// DiscountMultiplierGTE applies the GTE predicate on the "discount_multiplier" field.
func DiscountMultiplierGTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldDiscountMultiplier, v))
}

// DiscountMultiplierLT applies the LT predicate on the "discount_multiplier" field.
func DiscountMultiplierLT(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldDiscountMultiplier, v))
}

// DiscountMultiplierLTE applies the LTE predicate on the "discount_multiplier" field.
func DiscountMultiplierLTE(v float64) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldDiscountMultiplier, v))
}

// FeaturesEQ applies the EQ predicate on the "features" field.
func FeaturesEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldFeatures, v))
}

// FeaturesNEQ applies the NEQ predicate on the "features" field.
func FeaturesNEQ(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldFeatures, v))
}

// FeaturesIn applies the In predicate on the "features" field.
func FeaturesIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldFeatures, vs...))
}

// FeaturesNotIn applies the NotIn predicate on the "features" field.
func FeaturesNotIn(vs ...string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldFeatures, vs...))
}

// FeaturesGT applies the GT predicate on the "features" field.
func FeaturesGT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldFeatures, v))
}

// FeaturesGTE applies the GTE predicate on the "features" field.
func FeaturesGTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldFeatures, v))
}

// FeaturesLT applies the LT predicate on the "features" field.
func FeaturesLT(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldFeatures, v))
}

// FeaturesLTE applies the LTE predicate on the "features" field.
func FeaturesLTE(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldFeatures, v))
}

// FeaturesContains applies the Contains predicate on the "features" field.
func FeaturesContains(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContains(FieldFeatures, v))
}

// FeaturesHasPrefix applies the HasPrefix predicate on the "features" field.
func FeaturesHasPrefix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasPrefix(FieldFeatures, v))
}

// FeaturesHasSuffix applies the HasSuffix predicate on the "features" field.
func FeaturesHasSuffix(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldHasSuffix(FieldFeatures, v))
}

// FeaturesEqualFold applies the EqualFold predicate on the "features" field.
func FeaturesEqualFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEqualFold(FieldFeatures, v))
}

// FeaturesContainsFold applies the ContainsFold predicate on the "features" field.
func FeaturesContainsFold(v string) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldContainsFold(FieldFeatures, v))
}

// BenefitsIsNil applies the IsNil predicate on the "benefits" field.
func BenefitsIsNil() predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIsNull(FieldBenefits))
}

// BenefitsNotNil applies the NotNil predicate on the "benefits" field.
func BenefitsNotNil() predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotNull(FieldBenefits))
}

// ForSaleEQ applies the EQ predicate on the "for_sale" field.
func ForSaleEQ(v bool) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldForSale, v))
}

// ForSaleNEQ applies the NEQ predicate on the "for_sale" field.
func ForSaleNEQ(v bool) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldForSale, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VIPLevel {
	return predicate.VIPLevel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMemberships applies the HasEdge predicate on the "memberships" edge.
func HasMemberships() predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembershipsTable, MembershipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembershipsWith applies the HasEdge predicate on the "memberships" edge with a given conditions (other predicates).
func HasMembershipsWith(preds ...predicate.UserVIPMembership) predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := newMembershipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRedeemCodes applies the HasEdge predicate on the "redeem_codes" edge.
func HasRedeemCodes() predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RedeemCodesTable, RedeemCodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRedeemCodesWith applies the HasEdge predicate on the "redeem_codes" edge with a given conditions (other predicates).
func HasRedeemCodesWith(preds ...predicate.RedeemCode) predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := newRedeemCodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.VIPLevel {
	return predicate.VIPLevel(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VIPLevel) predicate.VIPLevel {
	return predicate.VIPLevel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VIPLevel) predicate.VIPLevel {
	return predicate.VIPLevel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VIPLevel) predicate.VIPLevel {
	return predicate.VIPLevel(sql.NotPredicates(p))
}
